version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gestion-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_ingenieria
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # ¡OJO! Asegúrate de que la carpeta 'sql' esté dentro de 'demo'
      - ./sql/ddl_ingenieria.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gestion-net

  backend:
    build: ./backend # Docker buscará la carpeta 'backend' dentro de 'demo'
    container_name: gestion-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestion_ingenieria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8082:8082"
    networks:
      - gestion-net

  frontend:
    build: ./frontend # Docker buscará la carpeta 'frontend' dentro de 'demo'
    container_name: gestion-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - gestion-net

volumes:
  db_data:


networks:
  gestion-net:
    driver: bridge
