-- ======================================================
-- 1. ESTRUCTURA (PostgreSQL / Supabase)
-- ======================================================

-- 1.1 TABLA USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(50) DEFAULT 'LECTURA',
    email VARCHAR(100),
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 1.2 TABLA CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido1 VARCHAR(50) NOT NULL,
    apellido2 VARCHAR(50),
    dni VARCHAR(15) NOT NULL UNIQUE,
    direccion_fiscal_completa VARCHAR(255),
    codigo_postal VARCHAR(10),
    cuenta_bancaria VARCHAR(34),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL
);

-- 1.3 TABLA LOCALES
CREATE TABLE IF NOT EXISTS locales (
    id_local BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nombre_titular VARCHAR(50) NOT NULL,
    apellido1_titular VARCHAR(50) NOT NULL,
    apellido2_titular VARCHAR(50),
    dni_titular VARCHAR(15),
    cups VARCHAR(22) NULL,
    referencia_catastral VARCHAR(20) NULL,
    direccion_completa VARCHAR(255) NOT NULL,
    latitud DECIMAL(10, 8) NULL,
    longitud DECIMAL(11, 8) NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    CONSTRAINT fk_local_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 1.4 TABLA CONTRATOS
CREATE TABLE IF NOT EXISTS contratos (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_local BIGINT NOT NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(50) NOT NULL,
    ce_previo VARCHAR(50) DEFAULT 'Pendiente',
    ce_post VARCHAR(50) DEFAULT 'Pendiente',
    enviado_cee_post BOOLEAN DEFAULT FALSE,
    licencia_obras VARCHAR(50) DEFAULT 'No requerida',
    mtd BOOLEAN DEFAULT FALSE,
    planos BOOLEAN DEFAULT FALSE,
    subvencion_estado VARCHAR(50) DEFAULT 'No solicitada',
    libro_edif_incluido BOOLEAN DEFAULT FALSE,
    observaciones TEXT NULL,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    CONSTRAINT fk_contrato_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_contrato_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE,
    CONSTRAINT chk_periodo_contrato CHECK (fecha_vencimiento >= fecha_inicio)
);

-- 1.5 TABLA TRAMITES_CONTRATO
CREATE TABLE IF NOT EXISTS tramites_contrato (
    id_tramite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato BIGINT NOT NULL,
    tipo_tramite VARCHAR(255) NOT NULL,
    estado VARCHAR(50) DEFAULT 'Pendiente',
    tecnico_asignado VARCHAR(100) NULL,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    detalle_seguimiento TEXT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion TIMESTAMPTZ NULL,
    CONSTRAINT fk_tramite_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) ON DELETE CASCADE
);

-- 1.6 TABLAS PROVEEDORES
CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR(100) NOT NULL,
    razon_social VARCHAR(100),
    es_autonomo BOOLEAN DEFAULT FALSE,
    cif VARCHAR(20) NOT NULL,
    direccion_fiscal VARCHAR(255),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema'
);

CREATE TABLE IF NOT EXISTS proveedor_oficios (
    id_oficio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    oficio VARCHAR(100) NOT NULL,
    CONSTRAINT fk_oficio_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS proveedor_contactos (
    id_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cargo VARCHAR(100),
    telefono VARCHAR(20),
    email VARCHAR(100),
    CONSTRAINT fk_contacto_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

-- 1.7 TABLA SEGUIMIENTO_TRAMITES
CREATE TABLE IF NOT EXISTS seguimiento_tramites (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_creador BIGINT NOT NULL,
    id_proveedor BIGINT NULL,
    comentario TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    estado VARCHAR(50) DEFAULT 'Pendiente',
    CONSTRAINT fk_seg_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE,
    CONSTRAINT fk_seg_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_creador FOREIGN KEY (id_creador) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE SET NULL
);

-- 1.8 TABLAS DE ARCHIVOS
CREATE TABLE IF NOT EXISTS archivos_cliente (
    id_archivo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    categoria VARCHAR(100) DEFAULT 'Otros',
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS archivos_tramite (
    id_archivo_t BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE
);

-- 1.9 TABLA AUDITORIA
CREATE TABLE IF NOT EXISTS auditoria_sistema (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(50) NOT NULL,
    id_registro BIGINT NOT NULL,
    campo_modificado VARCHAR(50),
    valor_anterior TEXT,
    valor_nuevo TEXT,
    fecha_cambio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_bd VARCHAR(100)
);

-- 1.10 TABLA SESIONES
CREATE TABLE IF NOT EXISTS auditoria_sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    nombre_usuario VARCHAR(50) NOT NULL,
    fecha_inicio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMPTZ NULL,
    ip_acceso VARCHAR(45),
    estado VARCHAR(20) DEFAULT 'Conectado',
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- 1.11 TABLA PRESUPUESTOS
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2) DEFAULT 0,
    total_sin_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Borrador',
    CONSTRAINT fk_presupuesto_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT
);

-- 1.12 TABLA PRESUPUESTO_LINEAS
CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL,
    orden INT NOT NULL,
    producto_id BIGINT NULL,
    producto_texto VARCHAR(255) NULL,
    concepto VARCHAR(255) NOT NULL,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    cantidad NUMERIC(12, 2) NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    total_linea NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_linea_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE
);

-- Si la tabla ya existia previamente, aseguramos la columna nueva
ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS producto_texto VARCHAR(255);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS iva_porcentaje NUMERIC(5, 2) DEFAULT 21;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS total_sin_iva NUMERIC(12, 2) DEFAULT 0;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS total_con_iva NUMERIC(12, 2) DEFAULT 0;

-- ======================================================
-- 2. VISTAS
-- ======================================================

CREATE OR REPLACE VIEW vista_estado_contratos AS
SELECT
    c.id_contrato,
    cl.id_cliente,
    cl.dni as dni_cliente,
    CONCAT(cl.apellido1, ' ', COALESCE(cl.apellido2, ''), ' , ', cl.nombre) AS nombre_cliente,
    l.direccion_completa,
    c.tipo_contrato,
    c.fecha_alta,
    c.fecha_vencimiento,
    CASE
        WHEN c.fecha_vencimiento < CURRENT_DATE THEN 'VENCIDO'
        ELSE 'ACTIVO'
    END AS estado
FROM contratos c
JOIN clientes cl ON c.id_cliente = cl.id_cliente
JOIN locales l ON c.id_local = l.id_local;

-- ======================================================
-- 3. DATOS DE PRUEBA COMPLETOS
-- ======================================================

-- 6 Usuarios
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) VALUES 
('jefe_admin', 'admin123', 'ADMIN', 'jefeadmin@insene.com'),
('carlos_tec', 'pass123', 'TÉCNICO', 'carlos.tec@insene.com'),
('marta_tec', 'pass123', 'TÉCNICO', 'marta.tec@insene.com'),
('raul_tec', 'pass123', 'TÉCNICO', 'raul.tec@insene.com'),
('elena_tec', 'pass123', 'TÉCNICO', 'elena.tec@insene.com'),
('pablo_tec', 'pass123', 'TÉCNICO', 'pablo.tec@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- 11 Clientes (idempotente por DNI)
INSERT INTO clientes (nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
SELECT *
FROM (VALUES
    ('Jose', 'Brenes', 'Oliva', '75892994D', 'Calle Mina 4, Arahal', '41600', 'ES1234567890123456789012', 'jefe_admin'),
    ('Ana', 'García', 'López', '12345678Z', 'Avda. Constitución 12, Sevilla', '41001', 'ES9876543210987654321098', 'jefe_admin'),
    ('Manuel', 'Sánchez', 'Pérez', '23456789X', 'Calle Real 45, Alcalá de Guadaíra', '41500', 'ES8765432109876543210987', 'jefe_admin'),
    ('María', 'Rodríguez', 'Ruiz', '34567890C', 'Plaza Mayor 1, Dos Hermanas', '41700', 'ES7654321098765432109876', 'jefe_admin'),
    ('David', 'Martínez', 'Jiménez', '45678901V', 'Calle Betis 8, Sevilla', '41010', 'ES6543210987654321098765', 'jefe_admin'),
    ('Lucía', 'Hernández', 'Muñoz', '56789012B', 'Calle Larga 22, Arahal', '41600', 'ES5432109876543210987654', 'jefe_admin'),
    ('Javier', 'Díaz', 'Moreno', '67890123N', 'Calle Ancha 15, Paradas', '41610', 'ES4321098765432109876543', 'jefe_admin'),
    ('Elena', 'Álvarez', 'Serrano', '78901234M', 'Calle Sierpes 3, Sevilla', '41004', 'ES3210987654321098765432', 'jefe_admin'),
    ('Pablo', 'Romero', 'Navarro', '89012345Q', 'Calle Nueva 10, Marchena', '41620', 'ES2109876543210987654321', 'jefe_admin'),
    ('Marta', 'Torres', 'Castro', '90123456W', 'Calle Feria 55, Sevilla', '41003', 'ES1098765432109876543210', 'jefe_admin'),
    ('Antonio', 'Vázquez', 'Blanco', '01234567E', 'Calle Pureza 2, Sevilla', '41011', 'ES0987654321098765432109', 'jefe_admin')
) AS v(nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
WHERE NOT EXISTS (
    SELECT 1 FROM clientes c WHERE c.dni = v.dni
);

-- 11 Locales (idempotente por cliente+dirección+cups+ref)
INSERT INTO locales (id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
SELECT *
FROM (VALUES
    (1, 'Jose', 'Brenes', '75892994D', 'ES0021000012345678AB1F', '1234567TG8901S0001FF', 'Calle Mina 4, Arahal', 37.2628, -5.4772, 'jefe_admin'),
    (2, 'Ana', 'García', '12345678Z', 'ES0021000087654321AB2G', '0869501QA5406N0003HI', 'Calle Diputación 250, Barcelona', 41.3887, 2.1645, 'jefe_admin'),
    (3, 'Manuel', 'Sánchez', '23456789X', 'ES0021000076543210AB3H', '6029215TF7760G0001AK', 'Avda. Los Majuelos 30, S.C. Tenerife', 28.4550, -16.2941, 'jefe_admin'),
    (4, 'María', 'Rodríguez', '34567890C', 'ES0021000065432109AB4I', '4961312UG1846S0002FU', 'Calle Real 1, Sevilla', 37.3828, -5.9731, 'jefe_admin'),
    (5, 'David', 'Martínez', '45678901V', 'ES0021000054321098AB5J', '6197808TG5369N0002BX', 'Calle Alcalá 45, Madrid', 40.4189, -3.6995, 'jefe_admin'),
    (6, 'Lucía', 'Hernández', '56789012B', 'ES0021000043210987AB6K', '1584301QB6318S0001LT', 'Calle Mayor 10, Valencia', 39.4699, -0.3763, 'jefe_admin'),
    (7, 'Javier', 'Díaz', '67890123N', 'ES0021000032109876AB7L', '0872229TG4107S0001HK', 'Calle Urquinaona 4, Barcelona', 41.3891, 2.1722, 'jefe_admin'),
    (8, 'Elena', 'Álvarez', '78901234M', 'ES0021000021098765AB8M', '4733421UG0643S0001GW', 'Avda. Palmera 15, Sevilla', 37.3592, -5.9864, 'jefe_admin'),
    (9, 'Pablo', 'Romero', '89012345Q', 'ES0021000010987654AB9N', '8073358TG4387S0001TF', 'Calle Pureza 80, Sevilla', 37.3822, -6.0003, 'jefe_admin'),
    (10, 'Marta', 'Torres', '90123456W', 'ES0021000009876543AB0O', '0165203TG4106N0001PH', 'Calle Feria 12, Sevilla', 37.3977, -5.9922, 'jefe_admin'),
    (11, 'Antonio', 'Vázquez', '01234567E', 'ES0021000098765432AB1P', '08020A0QB6300S0001PE', 'Polígono Industrial 5, Córdoba', 37.8882, -4.7794, 'jefe_admin')
) AS v(id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
WHERE NOT EXISTS (
    SELECT 1 FROM locales l
    WHERE l.id_cliente = v.id_cliente
      AND l.direccion_completa = v.direccion_completa
      AND COALESCE(l.cups, '') = COALESCE(v.cups, '')
      AND COALESCE(l.referencia_catastral, '') = COALESCE(v.referencia_catastral, '')
);

-- 11 Contratos (idempotente por claves naturales)
INSERT INTO contratos (id_cliente, id_local, fecha_inicio, fecha_vencimiento, tipo_contrato, creado_por)
SELECT *
FROM (VALUES
    (1, 1, '2025-01-01'::date, '2026-01-01'::date, 'Instalacion', 'jefe_admin'),
    (2, 2, '2025-02-01'::date, '2026-02-01'::date, 'Instalacion', 'jefe_admin'),
    (3, 3, '2025-02-15'::date, '2026-02-15'::date, 'Preventivo', 'jefe_admin'),
    (4, 4, '2025-03-01'::date, '2026-03-01'::date, 'Ampliacion', 'jefe_admin'),
    (5, 5, '2025-03-10'::date, '2026-03-10'::date, 'Instalacion', 'jefe_admin'),
    (6, 6, '2025-04-01'::date, '2026-04-01'::date, 'Preventivo', 'jefe_admin'),
    (7, 7, '2025-04-20'::date, '2026-04-20'::date, 'Ampliacion', 'jefe_admin'),
    (8, 8, '2025-05-01'::date, '2026-05-01'::date, 'Instalacion', 'jefe_admin'),
    (9, 9, '2025-05-15'::date, '2026-05-15'::date, 'Preventivo', 'jefe_admin'),
    (10, 10, '2025-06-01'::date, '2026-06-01'::date, 'Ampliacion', 'jefe_admin'),
    (11, 11, '2025-06-10'::date, '2026-06-10'::date, 'Instalacion', 'jefe_admin')
) AS v(id_cliente, id_local, fecha_inicio, fecha_vencimiento, tipo_contrato, creado_por)
WHERE NOT EXISTS (
    SELECT 1 FROM contratos c
    WHERE c.id_cliente = v.id_cliente
      AND c.id_local = v.id_local
      AND c.fecha_inicio = v.fecha_inicio
      AND c.fecha_vencimiento = v.fecha_vencimiento
      AND c.tipo_contrato = v.tipo_contrato
);

-- 10 Proveedores (idempotente por CIF)
INSERT INTO proveedores (nombre_comercial, razon_social, es_autonomo, cif, direccion_fiscal, creado_por)
SELECT *
FROM (VALUES
    ('Electricidad García SL', 'Electricidad García Sociedad Limitada', FALSE, 'B12345678', 'Pol. Ind. Calonge, Calle A, 12, Sevilla', 'jefe_admin'),
    ('Carlos Fontanería', 'Carlos Pérez Gómez', TRUE, '12345678Z', 'Calle Betis 45, Sevilla', 'jefe_admin'),
    ('Construcciones Modesto', 'Modesto Construcciones SA', FALSE, 'A87654321', 'Avda. de la Paz 10, Alcalá de Guadaíra', 'jefe_admin'),
    ('Climatización Del Sur', 'ClimaSur Instalaciones SL', FALSE, 'B11223344', 'Calle Refrigeración 5, Dos Hermanas', 'jefe_admin'),
    ('Topografía y Medición', 'Ana Ruiz Topógrafa', TRUE, '23456789X', 'Plaza de Cuba 3, Sevilla', 'jefe_admin'),
    ('Carpintería Hnos. López', 'Carpintería López CB', FALSE, 'E55667788', 'Calle Madera 8, Utrera', 'jefe_admin'),
    ('Pinturas Lozano', 'Juan Lozano Pintor', TRUE, '34567890C', 'Calle Arco Iris 2, Mairena del Aljarafe', 'jefe_admin'),
    ('Silence Acústica', 'Ingeniería Silence SL', FALSE, 'B99887766', 'Parque Tecnológico Cartuja, Sevilla', 'jefe_admin'),
    ('Excavaciones Tierra', 'Excavaciones Tierra SL', FALSE, 'B44332211', 'Carretera Carmona Km 5', 'jefe_admin'),
    ('Seguridad 24h', 'Alarmas y Sistemas SL', FALSE, 'B66778899', 'Avda. República Argentina 20, Sevilla', 'jefe_admin')
) AS v(nombre_comercial, razon_social, es_autonomo, cif, direccion_fiscal, creado_por)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedores p WHERE p.cif = v.cif
);

-- Oficios de los proveedores (idempotente por proveedor+oficio)
INSERT INTO proveedor_oficios (id_proveedor, oficio)
SELECT *
FROM (VALUES
    (1, 'Electricidad'), (1, 'Baja Tensión'),
    (2, 'Fontanería'), (2, 'Gas'),
    (3, 'Albañilería'), (3, 'Reformas'),
    (4, 'Climatización'), (4, 'Ventilación'),
    (5, 'Topografía'),
    (6, 'Carpintería Madera'), (6, 'Ebanistería'),
    (7, 'Pintura'), (7, 'Revestimientos'),
    (8, 'Ingeniería Acústica'), (8, 'Mediciones'),
    (9, 'Movimiento de Tierras'), (9, 'Excavación'),
    (10, 'Sistemas Seguridad'), (10, 'PCI')
) AS v(id_proveedor, oficio)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedor_oficios po
    WHERE po.id_proveedor = v.id_proveedor AND po.oficio = v.oficio
);

-- Contactos de los proveedores (idempotente por proveedor+nombre+email)
INSERT INTO proveedor_contactos (id_proveedor, nombre, cargo, telefono, email)
SELECT *
FROM (VALUES
    (1, 'Manuel García', 'Gerente', '600111222', 'mg@garciasl.com'),
    (2, 'Carlos Pérez', 'Autónomo', '611222333', 'carlosperez@fontaneria.com'),
    (3, 'Modesto Rodríguez', 'Jefe de Obra', '622333444', 'obras@modesto.com'),
    (4, 'Lucía Méndez', 'Administración', '633444555', 'admin@climasur.com'),
    (5, 'Ana Ruiz', 'Topógrafa', '644555666', 'ana.ruiz@topografia.com'),
    (6, 'Pedro López', 'Encargado Taller', '655666777', 'pedro@carpinterialopez.com'),
    (7, 'Juan Lozano', 'Pintor', '666777888', 'juan@pinturaslozano.com'),
    (8, 'Elena Valls', 'Ingeniera Acústica', '677888999', 'elena@silence.com'),
    (9, 'Roberto Tierra', 'Jefe Maquinaria', '688999000', 'roberto@excavaciones.com'),
    (10, 'Sonia Vigil', 'Comercial', '699000111', 'sonia@seguridad24.com')
) AS v(id_proveedor, nombre, cargo, telefono, email)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedor_contactos pc
    WHERE pc.id_proveedor = v.id_proveedor
      AND pc.nombre = v.nombre
      AND COALESCE(pc.email, '') = COALESCE(v.email, '')
);

-- Presupuestos (reset y datos reales sector solar)
TRUNCATE TABLE presupuesto_lineas, presupuestos RESTART IDENTITY CASCADE;

INSERT INTO presupuestos (cliente_id, vivienda_id, codigo_referencia, fecha, total, total_sin_iva, total_con_iva, estado)
VALUES
    (1, 1, 'PRES-SOLAR-001', '2026-02-01'::date, 4114.00, 3400.00, 4114.00, 'Borrador'),
    (2, 2, 'PRES-SOLAR-002', '2026-02-03'::date, 9002.40, 7440.00, 9002.40, 'Enviado'),
    (3, 3, 'PRES-SOLAR-003', '2026-02-05'::date, 520.30, 430.00, 520.30, 'Borrador'),
    (4, 4, 'PRES-SOLAR-004', '2026-02-07'::date, 10950.50, 9050.00, 10950.50, 'Aceptado');

INSERT INTO presupuesto_lineas (
    presupuesto_id, orden, producto_id, producto_texto, concepto, iva_porcentaje, cantidad, precio_unitario, total_linea
)
SELECT p.id_presupuesto, v.orden, v.producto_id, v.producto_texto, v.concepto, v.iva_porcentaje, v.cantidad, v.precio_unitario, v.total_linea
FROM (VALUES
    -- Caso 1: Autoconsumo Residencial Básico (3kWp)
    ('PRES-SOLAR-001', 1, NULL::bigint, '8x Módulo Fotovoltaico JA Solar 455W Mono PERC', 'Línea 1', 21, 8.00, 150.00, 1200.00),
    ('PRES-SOLAR-001', 2, NULL::bigint, 'Inversor Huawei SUN2000-3KTL-L1 Híbrido', 'Línea 2', 21, 1.00, 950.00, 950.00),
    ('PRES-SOLAR-001', 3, NULL::bigint, 'Estructura Coplanar Aluminio 8 Módulos', 'Línea 3', 21, 1.00, 350.00, 350.00),
    ('PRES-SOLAR-001', 4, NULL::bigint, 'Instalación, Montaje y Legalización (CIE)', 'Línea 4', 21, 1.00, 900.00, 900.00),

    -- Caso 2: Vivienda Unifamiliar con Batería (5kWp + Acumulación)
    ('PRES-SOLAR-002', 1, NULL::bigint, '12x Panel Canadian Solar 550W HiKu6', 'Línea 1', 21, 12.00, 170.00, 2040.00),
    ('PRES-SOLAR-002', 2, NULL::bigint, 'Inversor Fronius Primo GEN24 5.0 Plus', 'Línea 2', 21, 1.00, 1200.00, 1200.00),
    ('PRES-SOLAR-002', 3, NULL::bigint, 'Batería BYD Battery-Box Premium HVS 5.1', 'Línea 3', 21, 1.00, 3000.00, 3000.00),
    ('PRES-SOLAR-002', 4, NULL::bigint, 'Mano de obra, Cableado y Protecciones DC/AC', 'Línea 4', 21, 1.00, 1200.00, 1200.00),

    -- Caso 3: Mantenimiento y Revisión
    ('PRES-SOLAR-003', 1, NULL::bigint, 'Limpieza técnica de campo solar (20 módulos)', 'Línea 1', 21, 1.00, 180.00, 180.00),
    ('PRES-SOLAR-003', 2, NULL::bigint, 'Revisión termográfica de cuadros e inversor', 'Línea 2', 21, 1.00, 250.00, 250.00),

    -- Caso 4: Kit Aislada (Casa de Campo)
    ('PRES-SOLAR-004', 1, NULL::bigint, 'Kit Victron MultiPlus-II 48/3000 + Cerbo GX', 'Línea 1', 21, 1.00, 1450.00, 1450.00),
    ('PRES-SOLAR-004', 2, NULL::bigint, '4x Batería Pylontech US3000C 3.5kWh LiFePo4', 'Línea 2', 21, 4.00, 1600.00, 6400.00),
    ('PRES-SOLAR-004', 3, NULL::bigint, 'Material vario e instalación eléctrica', 'Línea 3', 21, 1.00, 1200.00, 1200.00)
) AS v(codigo_referencia, orden, producto_id, producto_texto, concepto, iva_porcentaje, cantidad, precio_unitario, total_linea)
JOIN presupuestos p ON p.codigo_referencia = v.codigo_referencia;

-- ======================================================
-- 4. PERMISOS (Supabase)
-- ======================================================
DO $$
DECLARE
  target_role text := 'postgres';
BEGIN
  EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', target_role);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I', target_role);
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', target_role);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I', target_role);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO %I', target_role);
END $$;