spring.application.name=gestion-backend
spring.profiles.active=${APP_PROFILE:shared}

# --- JPA / HIBERNATE ---
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Madrid

# --- TIMEZONE ---
spring.jackson.time-zone=Europe/Madrid

# --- APP SPECIFIC (JWT) ---
app.jwt.secret=9a4f2c8d3b7e1f0g2h5j8k9l0m1n4o7p2q5r8s1t4u7v0w3x6y9z
app.jwt.expiration-ms=86400000
app.seed.admin=true

# --- SERVER ---
server.port=8082

# --- FILE UPLOAD ---
app.file.upload-dir=uploads