-- ======================================================
-- 1. ESTRUCTURA (PostgreSQL / Supabase)
-- ======================================================

-- 1.1 TABLA USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(50) DEFAULT 'LECTURA',
    email VARCHAR(100),
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 1.2 TABLA CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido1 VARCHAR(50) NOT NULL,
    apellido2 VARCHAR(50),
    dni VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100),
    direccion_fiscal_completa VARCHAR(255),
    codigo_postal VARCHAR(10),
    cuenta_bancaria VARCHAR(34),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL
);


CREATE TABLE IF NOT EXISTS cliente_telefonos (
    id_telefono BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    descripcion VARCHAR(50), -- Ej: Móvil, Trabajo, Casa
    CONSTRAINT fk_tel_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 1.3 TABLA LOCALES
CREATE TABLE IF NOT EXISTS locales (
    id_local BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NULL,
    nombre_titular VARCHAR(50) NOT NULL,
    apellido1_titular VARCHAR(50) NOT NULL,
    apellido2_titular VARCHAR(50),
    dni_titular VARCHAR(15),
    cups VARCHAR(22) NULL,
    referencia_catastral VARCHAR(20) NULL,
    direccion_completa VARCHAR(255) NOT NULL,
    latitud DECIMAL(10, 8) NULL,
    longitud DECIMAL(11, 8) NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    CONSTRAINT fk_local_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 1.3.1 TABLAS DE ÁREAS Y UBICACIONES (Nuevo)
CREATE TABLE IF NOT EXISTS local_areas (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    orden INTEGER DEFAULT 0,
    CONSTRAINT fk_area_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS local_ubicaciones (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    orden INTEGER DEFAULT 0,
    CONSTRAINT fk_ubicacion_area FOREIGN KEY (id_area) REFERENCES local_areas(id_area) ON DELETE CASCADE
);

-- 1.4 TABLA CONTRATOS
CREATE TABLE IF NOT EXISTS contratos (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_local BIGINT NOT NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(50) NOT NULL,
    ce_previo VARCHAR(50) DEFAULT 'Pendiente',
    ce_post VARCHAR(50) DEFAULT 'Pendiente',
    enviado_cee_post BOOLEAN DEFAULT FALSE,
    licencia_obras VARCHAR(50) DEFAULT 'No requerida',
    mtd BOOLEAN DEFAULT FALSE,
    planos BOOLEAN DEFAULT FALSE,
    subvencion_estado VARCHAR(50) DEFAULT 'No solicitada',
    libro_edif_incluido BOOLEAN DEFAULT FALSE,
    observaciones TEXT NULL,
    estado VARCHAR(50) DEFAULT 'Activo',
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    CONSTRAINT fk_contrato_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_contrato_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE,
    CONSTRAINT chk_periodo_contrato CHECK (fecha_vencimiento >= fecha_inicio)
);

-- 1.5 TABLA TRAMITES_CONTRATO
CREATE TABLE IF NOT EXISTS TRAMITES_CONTRATO (
    id_tramite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato BIGINT NOT NULL,
    tipo_tramite VARCHAR(255) NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    tecnico_asignado VARCHAR(255) NULL,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    facturado BOOLEAN DEFAULT FALSE,
    detalle_seguimiento TEXT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion TIMESTAMPTZ NULL,
    CONSTRAINT fk_tramite_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) ON DELETE CASCADE
);


-- 1.6 TABLAS PROVEEDORES
CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR(100) NOT NULL,
    razon_social VARCHAR(100),
    es_autonomo BOOLEAN DEFAULT FALSE,
    cif VARCHAR(20) NOT NULL,
    direccion_fiscal VARCHAR(255),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema'
);

-- ... (skipping lines) ...

-- 1.11 TABLA PRESUPUESTOS
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2) DEFAULT 0,
    total_sin_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Borrador',
    tipo_presupuesto VARCHAR(20) DEFAULT 'Obra',
    id_tramite BIGINT NULL, -- Nueva vinculación
    CONSTRAINT fk_presupuesto_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE SET NULL
);
-- 1.6.1 TABLA PRODUCTOS
CREATE TABLE IF NOT EXISTS productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_ref_producto VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL,
    coste NUMERIC(12, 2) NOT NULL,
    margen NUMERIC(5, 2) DEFAULT 0,
    iva NUMERIC(5, 2) DEFAULT 21,
    precio_venta NUMERIC(12, 2) DEFAULT 0,
    categoria VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS proveedor_oficios (
    id_oficio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    oficio VARCHAR(100) NOT NULL,
    CONSTRAINT fk_oficio_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROVEEDOR_CONTACTOS (
    id_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cargo VARCHAR(255),
    telefono VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT fk_contacto_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

-- 1.7 TABLA SEGUIMIENTO_TRAMITES
CREATE TABLE IF NOT EXISTS SEGUIMIENTO_TRAMITES (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_creador BIGINT NOT NULL,
    id_proveedor BIGINT NULL,
    comentario TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    CONSTRAINT fk_seg_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE CASCADE,
    CONSTRAINT fk_seg_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_creador FOREIGN KEY (id_creador) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE SET NULL
);

-- 1.8 TABLAS DE ARCHIVOS
CREATE TABLE IF NOT EXISTS archivos_cliente (
    id_archivo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    categoria VARCHAR(100) DEFAULT 'Otros',
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 1.7.5 TABLA AREAS_FUNCIONALES
CREATE TABLE IF NOT EXISTS areas_funcionales (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    orden INT,
    CONSTRAINT fk_area_func_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE
);

-- 1.7.6 TABLA AREA_FUNCIONAL_LINEAS
CREATE TABLE IF NOT EXISTS area_funcional_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL,
    producto_id BIGINT,
    producto_texto VARCHAR(255),
    concepto VARCHAR(255),
    cantidad NUMERIC(12, 2),
    accion_requerida VARCHAR(255),
    orden INT,
    CONSTRAINT fk_af_linea_area FOREIGN KEY (id_area) REFERENCES areas_funcionales(id_area) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS archivos_tramite (
    id_archivo_t BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE
);

-- 1.8.1 TABLA CRM_DOCUMENTS (Sistema Genérico)
CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    file_name_original VARCHAR(255) NOT NULL,
    file_name_system VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_type VARCHAR(255),
    size BIGINT,
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
create index if not exists idx_crm_docs_ref on crm_documents(entity_type, reference_id);

-- 1.9 TABLA AUDITORIA
CREATE TABLE IF NOT EXISTS auditoria_sistema (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(50) NOT NULL,
    id_registro BIGINT NOT NULL,
    campo_modificado VARCHAR(50),
    valor_anterior TEXT,
    valor_nuevo TEXT,
    fecha_cambio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_bd VARCHAR(100)
);

-- 1.10 TABLA SESIONES
CREATE TABLE IF NOT EXISTS auditoria_sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    nombre_usuario VARCHAR(50) NOT NULL,
    fecha_inicio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMPTZ NULL,
    fecha_ultima_actividad TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ip_acceso VARCHAR(45),
    estado VARCHAR(20) DEFAULT 'Conectado',
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- Asegurar columna para migraciones de bases de datos existentes
ALTER TABLE auditoria_sesiones ADD COLUMN IF NOT EXISTS fecha_ultima_actividad TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- 1.11 TABLA PRESUPUESTOS
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2) DEFAULT 0,
    total_sin_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Borrador',
    tipo_presupuesto VARCHAR(20) DEFAULT 'Obra',
    id_tramite BIGINT NULL,
    fecha_aceptacion TIMESTAMPTZ NULL,
    dias_validez INT NULL,
    CONSTRAINT fk_presupuesto_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE SET NULL
);

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS tipo_presupuesto VARCHAR(20) DEFAULT 'Obra';

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS id_tramite BIGINT NULL;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS fecha_aceptacion TIMESTAMPTZ NULL;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS dias_validez INT NULL;

ALTER TABLE presupuestos
    DROP CONSTRAINT IF EXISTS fk_presupuesto_tramite;

ALTER TABLE presupuestos
    ADD CONSTRAINT fk_presupuesto_tramite 
    FOREIGN KEY (id_tramite) 
    REFERENCES tramites_contrato(id_tramite) 
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_presupuestos_tramite ON presupuestos(id_tramite);

UPDATE presupuestos
SET tipo_presupuesto = 'Obra'
WHERE tipo_presupuesto IS NULL;


-- 1.12 TABLA PRESUPUESTO_LINEAS
-- Si la tabla existe con id_linea UUID, la recreamos en BIGINT (entorno dev)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'presupuesto_lineas'
      AND column_name = 'id_linea'
      AND data_type = 'uuid'
  ) THEN
    DROP TABLE IF EXISTS presupuesto_lineas CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL,
    orden INT NOT NULL,
    producto_id BIGINT NULL,
    producto_texto VARCHAR(255) NULL,
    concepto VARCHAR(255) NOT NULL,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    coste_unitario NUMERIC(12, 2),
    factor_margen NUMERIC(6, 2) DEFAULT 1.00,
    total_coste NUMERIC(12, 2),
    pvp_unitario NUMERIC(12, 2),
    total_pvp NUMERIC(12, 2),
    importe_iva NUMERIC(12, 2),
    total_final NUMERIC(12, 2),
    total_linea NUMERIC(12, 2),
    tipo_jerarquia VARCHAR(20) DEFAULT 'PARTIDA',
    codigo_visual VARCHAR(20),
    padre_id BIGINT NULL,
    num_visitas INT DEFAULT 0,
    CONSTRAINT fk_linea_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE
);

-- 1.13 MANTENIMIENTO PREVENTIVO
CREATE TABLE IF NOT EXISTS PRESUPUESTOS_PREVENTIVOS (
    id_presupuesto_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NULL,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(255) DEFAULT 'Borrador',
    notas TEXT,
    CONSTRAINT fk_pp_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_pp_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT
);

-- 1.14 AGENDA DE CITAS
CREATE TABLE IF NOT EXISTS CITAS (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    estado VARCHAR(255) DEFAULT 'Programada',
    enlace_remoto TEXT,
    notas TEXT,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ NOT NULL,
    recordatorio_min INT DEFAULT 15,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cita_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_cita_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_citas_fecha_inicio ON CITAS (fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_citas_usuario ON CITAS (usuario_id);

-- 1.15 CHAT (TIEMPO REAL)
CREATE TABLE IF NOT EXISTS chat_salas (
    id_sala BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    es_global BOOLEAN DEFAULT FALSE,
    tipo VARCHAR(20) DEFAULT 'GLOBAL',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_participantes (
    id_participante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sala_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_part_sala FOREIGN KEY (sala_id) REFERENCES chat_salas(id_sala) ON DELETE CASCADE,
    CONSTRAINT fk_part_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS chat_mensajes (
    id_mensaje BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sala_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    contenido TEXT NOT NULL,
    fecha_envio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_mensaje_sala FOREIGN KEY (sala_id) REFERENCES chat_salas(id_sala) ON DELETE CASCADE,
    CONSTRAINT fk_chat_mensaje_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS chat_adjuntos (
    id_adjunto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id BIGINT NOT NULL,
    url TEXT NOT NULL,
    tipo VARCHAR(50),
    nombre VARCHAR(255),
    CONSTRAINT fk_chat_adj_mensaje FOREIGN KEY (mensaje_id) REFERENCES chat_mensajes(id_mensaje) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_menciones (
    id_mencion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_chat_mencion_mensaje FOREIGN KEY (mensaje_id) REFERENCES chat_mensajes(id_mensaje) ON DELETE CASCADE,
    CONSTRAINT fk_chat_mencion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_lecturas (
    id_lectura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    leido BOOLEAN DEFAULT TRUE,
    fecha_lectura TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_lectura_mensaje FOREIGN KEY (mensaje_id) REFERENCES chat_mensajes(id_mensaje) ON DELETE CASCADE,
    CONSTRAINT fk_chat_lectura_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_mensajes_sala_fecha ON chat_mensajes (sala_id, fecha_envio);
CREATE INDEX IF NOT EXISTS idx_chat_mensajes_usuario ON chat_mensajes (usuario_id);
CREATE INDEX IF NOT EXISTS idx_chat_lecturas_usuario ON chat_lecturas (usuario_id);

INSERT INTO chat_salas (nombre, es_global)
SELECT 'General', TRUE
WHERE NOT EXISTS (SELECT 1 FROM chat_salas WHERE es_global = TRUE);

ALTER TABLE PRESUPUESTOS_PREVENTIVOS
    ADD COLUMN IF NOT EXISTS presupuesto_id BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_pp_presupuesto_base'
  ) THEN
    ALTER TABLE PRESUPUESTOS_PREVENTIVOS
      ADD CONSTRAINT fk_pp_presupuesto_base
      FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class WHERE relname = 'uq_pp_presupuesto_base'
  ) THEN
    CREATE UNIQUE INDEX uq_pp_presupuesto_base ON PRESUPUESTOS_PREVENTIVOS(presupuesto_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS PRESUPUESTOS_PREVENTIVOS_TAREAS (
    id_tarea_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_pp_tarea_presupuesto FOREIGN KEY (presupuesto_prev_id) REFERENCES PRESUPUESTOS_PREVENTIVOS(id_presupuesto_prev) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CONTRATOS_MANTENIMIENTO (
    id_contrato_mant BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    estado VARCHAR(255) DEFAULT 'Activo',
    creado_por VARCHAR(100),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cm_presupuesto FOREIGN KEY (presupuesto_prev_id) REFERENCES PRESUPUESTOS_PREVENTIVOS(id_presupuesto_prev) ON DELETE RESTRICT,
    CONSTRAINT fk_cm_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_cm_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT
);

ALTER TABLE CONTRATOS_MANTENIMIENTO
    ADD COLUMN IF NOT EXISTS contrato_id BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_cm_contrato_base'
  ) THEN
    ALTER TABLE CONTRATOS_MANTENIMIENTO
      ADD CONSTRAINT fk_cm_contrato_base
      FOREIGN KEY (contrato_id) REFERENCES contratos(id_contrato) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class WHERE relname = 'uq_cm_presupuesto_prev'
  ) THEN
    CREATE UNIQUE INDEX uq_cm_presupuesto_prev ON CONTRATOS_MANTENIMIENTO(presupuesto_prev_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS CONTRATOS_MANTENIMIENTO_TAREAS (
    id_tarea_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_cmt_contrato FOREIGN KEY (contrato_mant_id) REFERENCES CONTRATOS_MANTENIMIENTO(id_contrato_mant) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AVISOS_MANTENIMIENTO (
    id_aviso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL,
    fecha_programada DATE NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aviso_contrato FOREIGN KEY (contrato_mant_id) REFERENCES CONTRATOS_MANTENIMIENTO(id_contrato_mant) ON DELETE CASCADE,
    CONSTRAINT uq_aviso_fecha UNIQUE (contrato_mant_id, fecha_programada)
);

CREATE TABLE IF NOT EXISTS AVISOS_MANTENIMIENTO_DETALLE (
    id_aviso_det BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aviso_id BIGINT NOT NULL,
    tarea_contrato_id BIGINT NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    observaciones TEXT,
    CONSTRAINT fk_aviso_det_aviso FOREIGN KEY (aviso_id) REFERENCES AVISOS_MANTENIMIENTO(id_aviso) ON DELETE CASCADE,
    CONSTRAINT fk_aviso_det_tarea FOREIGN KEY (tarea_contrato_id) REFERENCES CONTRATOS_MANTENIMIENTO_TAREAS(id_tarea_contrato) ON DELETE RESTRICT
);

-- Si la tabla ya existia previamente, aseguramos la columna nueva
ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS producto_texto VARCHAR(255);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS iva_porcentaje NUMERIC(5, 2) DEFAULT 21;

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS coste_unitario NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS factor_margen NUMERIC(6, 2) DEFAULT 1.00;

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS total_coste NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS pvp_unitario NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS total_pvp NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS importe_iva NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS total_final NUMERIC(12, 2);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS tipo_jerarquia VARCHAR(20) DEFAULT 'PARTIDA';

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS codigo_visual VARCHAR(20);

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS padre_id BIGINT;

ALTER TABLE presupuesto_lineas
    ADD COLUMN IF NOT EXISTS num_visitas INT DEFAULT 0;

ALTER TABLE presupuesto_lineas
    ALTER COLUMN cantidad DROP NOT NULL;

ALTER TABLE presupuesto_lineas
    ALTER COLUMN precio_unitario DROP NOT NULL;

ALTER TABLE presupuesto_lineas
    ALTER COLUMN total_linea DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_constraint WHERE conname = 'fk_presupuesto_lineas_padre'
  ) THEN
      ALTER TABLE presupuesto_lineas
          ADD CONSTRAINT fk_presupuesto_lineas_padre
          FOREIGN KEY (padre_id) REFERENCES presupuesto_lineas(id_linea)
          ON DELETE CASCADE;
  END IF;
END $$;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS total_sin_iva NUMERIC(12, 2) DEFAULT 0;

ALTER TABLE presupuestos
    ADD COLUMN IF NOT EXISTS total_con_iva NUMERIC(12, 2) DEFAULT 0;

-- ======================================================
-- 2. VISTAS
-- ======================================================

CREATE OR REPLACE VIEW vista_estado_contratos AS
SELECT
    c.id_contrato,
    cl.id_cliente,
    cl.dni as dni_cliente,
    CONCAT(cl.apellido1, ' ', COALESCE(cl.apellido2, ''), ' , ', cl.nombre) AS nombre_cliente,
    l.direccion_completa,
    c.tipo_contrato,
    c.fecha_alta,
    c.fecha_vencimiento,
    CASE
        WHEN c.fecha_vencimiento < CURRENT_DATE THEN 'VENCIDO'
        ELSE 'ACTIVO'
    END AS estado
FROM contratos c
JOIN clientes cl ON c.id_cliente = cl.id_cliente
JOIN locales l ON c.id_local = l.id_local;

-- ======================================================
-- 3. DATOS DE PRUEBA COMPLETOS
-- ======================================================

-- 6 Usuarios (BCrypt)
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) VALUES 
('jefe_admin', '$2a$10$fx8sccd3svi33CcKUrH.BOfPEiC8Y.qWD1rYKkobZ2rporK45MmGi', 'ADMIN', 'jefeadmin@insene.com'),
('carlos_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'carlos.tec@insene.com'),
('marta_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'marta.tec@insene.com'),
('raul_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'raul.tec@insene.com'),
('elena_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'elena.tec@insene.com'),
('pablo_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'pablo.tec@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- 11 Clientes (idempotente por DNI)
INSERT INTO clientes (nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
SELECT v.nombre, v.apellido1, v.apellido2, v.dni, v.direccion, v.cp, v.cuenta, 'jefe_admin'
FROM (VALUES
    ('Jose', 'Brenes', 'Oliva', '75892994D', 'Calle Mina 4, Arahal', '41600', 'ES1234567890123456789012'),
    ('Ana', 'García', 'López', '12345678Z', 'Avda. Constitución 12, Sevilla', '41001', 'ES9876543210987654321098'),
    ('Manuel', 'Sánchez', 'Pérez', '23456789X', 'Calle Real 45, Alcalá de Guadaíra', '41500', 'ES8765432109876543210987'),
    ('María', 'Rodríguez', 'Ruiz', '34567890C', 'Plaza Mayor 1, Dos Hermanas', '41700', 'ES7654321098765432109876'),
    ('David', 'Martínez', 'Jiménez', '45678901V', 'Calle Betis 8, Sevilla', '41010', 'ES6543210987654321098765'),
    ('Lucía', 'Hernández', 'Muñoz', '56789012B', 'Calle Larga 22, Arahal', '41600', 'ES5432109876543210987654'),
    ('Javier', 'Díaz', 'Moreno', '67890123N', 'Calle Ancha 15, Paradas', '41610', 'ES4321098765432109876543'),
    ('Elena', 'Álvarez', 'Serrano', '78901234M', 'Calle Sierpes 3, Sevilla', '41004', 'ES3210987654321098765432'),
    ('Pablo', 'Romero', 'Navarro', '89012345Q', 'Calle Nueva 10, Marchena', '41620', 'ES2109876543210987654321'),
    ('Marta', 'Torres', 'Castro', '90123456W', 'Calle Feria 55, Sevilla', '41003', 'ES1098765432109876543210'),
    ('Antonio', 'Vázquez', 'Blanco', '01234567E', 'Calle Pureza 2, Sevilla', '41011', 'ES0987654321098765432109')
) AS v(nombre, apellido1, apellido2, dni, direccion, cp, cuenta)
WHERE NOT EXISTS (SELECT 1 FROM clientes c WHERE c.dni = v.dni);

-- 11 Locales (vinculados por DNI del cliente)
INSERT INTO locales (id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
SELECT c.id_cliente, v.nombre, v.apellido1, v.dni, v.cups, v.ref_cat, v.direccion, v.lat, v.lon, 'jefe_admin'
FROM (VALUES
    ('75892994D', 'Jose', 'Brenes', '75892994D', 'ES0021000012345678AB1F', '1234567TG8901S0001FF', 'Calle Mina 4, Arahal', 37.2628, -5.4772),
    ('12345678Z', 'Ana', 'García', '12345678Z', 'ES0021000087654321AB2G', '0869501QA5406N0003HI', 'Calle Diputación 250, Barcelona', 41.3887, 2.1645),
    ('23456789X', 'Manuel', 'Sánchez', '23456789X', 'ES0021000076543210AB3H', '6029215TF7760G0001AK', 'Avda. Los Majuelos 30, S.C. Tenerife', 28.4550, -16.2941),
    ('34567890C', 'María', 'Rodríguez', '34567890C', 'ES0021000065432109AB4I', '4961312UG1846S0002FU', 'Calle Real 1, Sevilla', 37.3828, -5.9731),
    ('45678901V', 'David', 'Martínez', '45678901V', 'ES0021000054321098AB5J', '6197808TG5369N0002BX', 'Calle Alcalá 45, Madrid', 40.4189, -3.6995),
    ('56789012B', 'Lucía', 'Hernández', '56789012B', 'ES0021000043210987AB6K', '1584301QB6318S0001LT', 'Calle Mayor 10, Valencia', 39.4699, -0.3763),
    ('67890123N', 'Javier', 'Díaz', '67890123N', 'ES0021000032109876AB7L', '0872229TG4107S0001HK', 'Calle Urquinaona 4, Barcelona', 41.3891, 2.1722),
    ('78901234M', 'Elena', 'Álvarez', '78901234M', 'ES0021000021098765AB8M', '4733421UG0643S0001GW', 'Avda. Palmera 15, Sevilla', 37.3592, -5.9864),
    ('89012345Q', 'Pablo', 'Romero', '89012345Q', 'ES0021000010987654AB9N', '8073358TG4387S0001TF', 'Calle Pureza 80, Sevilla', 37.3822, -6.0003),
    ('90123456W', 'Marta', 'Torres', '90123456W', 'ES0021000009876543AB0O', '0165203TG4106N0001PH', 'Calle Feria 12, Sevilla', 37.3977, -5.9922),
    ('01234567E', 'Antonio', 'Vázquez', '01234567E', 'ES0021000098765432AB1P', '08020A0QB6300S0001PE', 'Polígono Industrial 5, Córdoba', 37.8882, -4.7794)
) AS v(dni_lookup, nombre, apellido1, dni, cups, ref_cat, direccion, lat, lon)
JOIN clientes c ON c.dni = v.dni_lookup
WHERE NOT EXISTS (SELECT 1 FROM locales l WHERE l.cups = v.cups);

-- 11 Contratos (vinculados por CUPS del local)
INSERT INTO contratos (id_cliente, id_local, fecha_inicio, fecha_vencimiento, tipo_contrato, creado_por)
SELECT l.id_cliente, l.id_local, v.f_ini::date, v.f_fin::date, v.tipo, 'jefe_admin'
FROM (VALUES
    ('ES0021000012345678AB1F', '2025-01-01', '2026-01-01', 'Instalacion'),
    ('ES0021000087654321AB2G', '2025-02-01', '2026-02-01', 'Instalacion'),
    ('ES0021000076543210AB3H', '2025-02-15', '2026-02-15', 'Preventivo'),
    ('ES0021000065432109AB4I', '2025-03-01', '2026-03-01', 'Ampliacion'),
    ('ES0021000054321098AB5J', '2025-03-10', '2026-03-10', 'Instalacion'),
    ('ES0021000043210987AB6K', '2025-04-01', '2026-04-01', 'Preventivo'),
    ('ES0021000032109876AB7L', '2025-04-20', '2026-04-20', 'Ampliacion'),
    ('ES0021000021098765AB8M', '2025-05-01', '2026-05-01', 'Instalacion'),
    ('ES0021000010987654AB9N', '2025-05-15', '2026-05-15', 'Preventivo'),
    ('ES0021000009876543AB0O', '2025-06-01', '2026-06-01', 'Ampliacion'),
    ('ES0021000098765432AB1P', '2025-06-10', '2026-06-10', 'Instalacion')
) AS v(cups_lookup, f_ini, f_fin, tipo)
JOIN locales l ON l.cups = v.cups_lookup
WHERE NOT EXISTS (
    SELECT 1 FROM contratos c 
    WHERE c.id_local = l.id_local AND c.fecha_inicio = v.f_ini::date
);

-- Trámites / Intervenciones (Asociados a Contratos por CUPS)
INSERT INTO tramites_contrato (id_contrato, tipo_tramite, estado, tecnico_asignado, fecha_seguimiento, es_urgente, facturado, detalle_seguimiento)
SELECT c.id_contrato, v.tipo, v.estado, 'carlos_tec', CURRENT_DATE + 5, v.urgente, false, v.detalle
FROM (VALUES
    ('ES0021000012345678AB1F', 'Legalización', 'Pendiente', false, 'Solicitud inicial de legalización'),
    ('ES0021000087654321AB2G', 'Instalación', 'En Progreso', true, 'Coordinar con técnico de zona'),
    ('ES0021000076543210AB3H', 'Mantenimiento', 'Pendiente', false, 'Revisión anual programada'),
    ('ES0021000065432109AB4I', 'Ampliación', 'Completado', false, 'Instalación de 3 módulos extra')
) AS v(cups_lookup, tipo, estado, urgente, detalle)
JOIN locales l ON l.cups = v.cups_lookup
JOIN contratos c ON c.id_local = l.id_local
WHERE NOT EXISTS (
    SELECT 1 FROM tramites_contrato tc 
    WHERE tc.id_contrato = c.id_contrato AND tc.tipo_tramite = v.tipo
);

-- Seguimientos de Trámites
INSERT INTO seguimiento_tramites (id_tramite, id_usuario, id_creador, comentario, estado)
SELECT t.id_tramite, u.id_usuario, u.id_usuario, 'Inicio del trámite confirmado. Documentación recibida.', 'En Progreso'
FROM tramites_contrato t
JOIN contratos c ON t.id_contrato = c.id_contrato
JOIN locales l ON c.id_local = l.id_local
JOIN usuarios u ON u.nombre_usuario = 'carlos_tec'
WHERE l.cups IN ('ES0021000012345678AB1F', 'ES0021000087654321AB2G')
AND NOT EXISTS (
    SELECT 1 FROM seguimiento_tramites st WHERE st.id_tramite = t.id_tramite
);


-- 10 Proveedores (idempotente por CIF)
INSERT INTO proveedores (nombre_comercial, razon_social, es_autonomo, cif, direccion_fiscal, creado_por)
SELECT *
FROM (VALUES
    ('Electricidad García SL', 'Electricidad García Sociedad Limitada', FALSE, 'B12345678', 'Pol. Ind. Calonge, Calle A, 12, Sevilla', 'jefe_admin'),
    ('Carlos Fontanería', 'Carlos Pérez Gómez', TRUE, '12345678Z', 'Calle Betis 45, Sevilla', 'jefe_admin'),
    ('Construcciones Modesto', 'Modesto Construcciones SA', FALSE, 'A87654321', 'Avda. de la Paz 10, Alcalá de Guadaíra', 'jefe_admin'),
    ('Climatización Del Sur', 'ClimaSur Instalaciones SL', FALSE, 'B11223344', 'Calle Refrigeración 5, Dos Hermanas', 'jefe_admin'),
    ('Topografía y Medición', 'Ana Ruiz Topógrafa', TRUE, '23456789X', 'Plaza de Cuba 3, Sevilla', 'jefe_admin'),
    ('Carpintería Hnos. López', 'Carpintería López CB', FALSE, 'E55667788', 'Calle Madera 8, Utrera', 'jefe_admin'),
    ('Pinturas Lozano', 'Juan Lozano Pintor', TRUE, '34567890C', 'Calle Arco Iris 2, Mairena del Aljarafe', 'jefe_admin'),
    ('Silence Acústica', 'Ingeniería Silence SL', FALSE, 'B99887766', 'Parque Tecnológico Cartuja, Sevilla', 'jefe_admin'),
    ('Excavaciones Tierra', 'Excavaciones Tierra SL', FALSE, 'B44332211', 'Carretera Carmona Km 5', 'jefe_admin'),
    ('Seguridad 24h', 'Alarmas y Sistemas SL', FALSE, 'B66778899', 'Avda. República Argentina 20, Sevilla', 'jefe_admin')
) AS v(nombre_comercial, razon_social, es_autonomo, cif, direccion_fiscal, creado_por)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedores p WHERE p.cif = v.cif
);

-- Productos (idempotente por cod_ref_producto)
INSERT INTO productos (cod_ref_producto, descripcion, coste, categoria) VALUES
('PNL-JKM550', 'Panel Solar Jinko Tiger Neo 550W Monocristalino', 145.50, 'Paneles Solares'),
('PNL-CS600', 'Panel Canadian Solar 600W HiKu6', 162.00, 'Paneles Solares'),
('PNL-LONG450', 'Panel Longi Solar 450W Black Frame', 110.00, 'Paneles Solares'),
('INV-HUA-5K', 'Inversor Híbrido Huawei SUN2000-5KTL-L1', 850.00, 'Inversores'),
('INV-FRO-GEN24', 'Inversor Fronius Primo GEN24 6.0 Plus', 1250.00, 'Inversores'),
('INV-SMA-ST10', 'Inversor de Red SMA Sunny Tripower 10.0', 1890.00, 'Inversores'),
('BAT-LUNA-5', 'Módulo Batería Huawei LUNA2000 5kWh', 2100.00, 'Baterías y Almacenamiento'),
('BAT-BYD-HVS', 'Batería BYD Battery-Box Premium HVS 5.1', 2450.00, 'Baterías y Almacenamiento'),
('EST-ALU-01', 'Perfil Aluminio 40x40 (Barra 3m) para Coplanar', 25.50, 'Estructuras y Fijaciones'),
('EST-GRAPA-END', 'Grapa Final Ajustable 30-40mm Negro', 1.20, 'Estructuras y Fijaciones'),
('EST-GRAPA-MID', 'Grapa Intermedia 30-40mm Negro', 1.35, 'Estructuras y Fijaciones'),
('CAB-SOL-6MM', 'Cable Solar H1Z2Z2-K 6mm² Rojo (Rollo 100m)', 115.00, 'Material Eléctrico'),
('CAB-SOL-6MM-B', 'Cable Solar H1Z2Z2-K 6mm² Negro (Rollo 100m)', 115.00, 'Material Eléctrico'),
('CON-MC4', 'Pareja Conectores MC4 Stäubli Original', 2.50, 'Material Eléctrico'),
('PROT-DC-2', 'Cuadro Protección DC 2 Strings 1000V', 85.00, 'Material Eléctrico')
ON CONFLICT (cod_ref_producto) DO NOTHING;

-- Oficios de los proveedores (idempotente por proveedor+oficio)
INSERT INTO proveedor_oficios (id_proveedor, oficio)
SELECT *
FROM (VALUES
    (1, 'Electricidad'), (1, 'Baja Tensión'),
    (2, 'Fontanería'), (2, 'Gas'),
    (3, 'Albañilería'), (3, 'Reformas'),
    (4, 'Climatización'), (4, 'Ventilación'),
    (5, 'Topografía'),
    (6, 'Carpintería Madera'), (6, 'Ebanistería'),
    (7, 'Pintura'), (7, 'Revestimientos'),
    (8, 'Ingeniería Acústica'), (8, 'Mediciones'),
    (9, 'Movimiento de Tierras'), (9, 'Excavación'),
    (10, 'Sistemas Seguridad'), (10, 'PCI')
) AS v(id_proveedor, oficio)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedor_oficios po
    WHERE po.id_proveedor = v.id_proveedor AND po.oficio = v.oficio
);

-- Contactos de los proveedores (idempotente por proveedor+nombre+email)
INSERT INTO proveedor_contactos (id_proveedor, nombre, cargo, telefono, email)
SELECT *
FROM (VALUES
    (1, 'Manuel García', 'Gerente', '600111222', 'mg@garciasl.com'),
    (2, 'Carlos Pérez', 'Autónomo', '611222333', 'carlosperez@fontaneria.com'),
    (3, 'Modesto Rodríguez', 'Jefe de Obra', '622333444', 'obras@modesto.com'),
    (4, 'Lucía Méndez', 'Administración', '633444555', 'admin@climasur.com'),
    (5, 'Ana Ruiz', 'Topógrafa', '644555666', 'ana.ruiz@topografia.com'),
    (6, 'Pedro López', 'Encargado Taller', '655666777', 'pedro@carpinterialopez.com'),
    (7, 'Juan Lozano', 'Pintor', '666777888', 'juan@pinturaslozano.com'),
    (8, 'Elena Valls', 'Ingeniera Acústica', '677888999', 'elena@silence.com'),
    (9, 'Roberto Tierra', 'Jefe Maquinaria', '688999000', 'roberto@excavaciones.com'),
    (10, 'Sonia Vigil', 'Comercial', '699000111', 'sonia@seguridad24.com')
) AS v(id_proveedor, nombre, cargo, telefono, email)
WHERE NOT EXISTS (
    SELECT 1 FROM proveedor_contactos pc
    WHERE pc.id_proveedor = v.id_proveedor
      AND pc.nombre = v.nombre
      AND COALESCE(pc.email, '') = COALESCE(v.email, '')
);

-- Presupuestos (jerarquía capítulos/partidas)
WITH t AS (
  SELECT tc.id_tramite, c.id_cliente, l.id_local
  FROM tramites_contrato tc
  JOIN contratos c ON tc.id_contrato = c.id_contrato
  JOIN locales l ON c.id_local = l.id_local
  WHERE l.cups = 'ES0021000012345678AB1F'
    AND tc.tipo_tramite = 'Legalización'
  LIMIT 1
),
p AS (
  INSERT INTO presupuestos (
    cliente_id, vivienda_id, codigo_referencia, fecha,
    total, total_sin_iva, total_con_iva, estado, id_tramite
  )
  SELECT id_cliente, id_local, 'PRES-HIER-001', CURRENT_DATE,
         14810.40, 12240.00, 14810.40, 'Borrador', id_tramite
  FROM t
  WHERE NOT EXISTS (SELECT 1 FROM presupuestos WHERE codigo_referencia = 'PRES-HIER-001')
  RETURNING id_presupuesto
),
cap01 AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 1, 'INGENIERÍA Y LEGALIZACIÓN', 'CAPITULO', '01' FROM p
  RETURNING id_linea
),
cap02 AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 2, 'GENERACIÓN FOTOVOLTAICA', 'CAPITULO', '02' FROM p
  RETURNING id_linea
),
cap03 AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 3, 'ELECTRICIDAD Y ACUMULACIÓN', 'CAPITULO', '03' FROM p
  RETURNING id_linea
),
cap04 AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 4, 'OBRA CIVIL / ALBAÑILERÍA', 'CAPITULO', '04' FROM p
  RETURNING id_linea
)
INSERT INTO presupuesto_lineas (
  presupuesto_id, orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, tipo_jerarquia, codigo_visual, padre_id
)
SELECT
  p.id_presupuesto, v.orden, v.concepto, v.cantidad, v.num_visitas, v.coste_unitario, v.factor_margen, v.total_coste, v.pvp_unitario, v.total_pvp,
  v.importe_iva, v.total_final, v.iva_porcentaje, v.precio_unitario, v.total_linea, 'PARTIDA', v.codigo_visual, c.id_linea
FROM p
JOIN (VALUES
  (1, 'Redacción de Proyecto Técnico de BT', 1, 0, 1200.00, 1.00, 1200.00, 1200.00, 1200.00, 252.00, 1452.00, 21, 1200.00, 1200.00, '01.01', 'cap01'),
  (2, 'Dirección de Obra y Coordinación CSS', 1, 0, 900.00, 1.00, 900.00, 900.00, 900.00, 189.00, 1089.00, 21, 900.00, 900.00, '01.02', 'cap01'),
  (3, 'Tasas Municipales (ICIO) y Gestión de Subvenciones', 1, 0, 450.00, 1.00, 450.00, 450.00, 450.00, 94.50, 544.50, 21, 450.00, 450.00, '01.03', 'cap01'),
  (4, '18x Módulo Jinko Solar Tiger Neo N-Type 475W', 18, 0, 160.00, 1.00, 2880.00, 160.00, 2880.00, 604.80, 3484.80, 21, 160.00, 2880.00, '02.01', 'cap02'),
  (5, 'Inversor Híbrido Huawei SUN2000-6KTL-L1', 1, 0, 1200.00, 1.00, 1200.00, 1200.00, 1200.00, 252.00, 1452.00, 21, 1200.00, 1200.00, '02.02', 'cap02'),
  (6, 'Estructura Coplanar K2 Systems (Aluminio)', 1, 0, 650.00, 1.00, 650.00, 650.00, 650.00, 136.50, 786.50, 21, 650.00, 650.00, '02.03', 'cap02'),
  (7, 'Batería Huawei LUNA2000 10kWh', 1, 0, 3400.00, 1.00, 3400.00, 3400.00, 3400.00, 714.00, 4114.00, 21, 3400.00, 3400.00, '03.01', 'cap03'),
  (8, 'Smart Power Sensor Huawei DTSU666-H', 1, 0, 180.00, 1.00, 180.00, 180.00, 180.00, 37.80, 217.80, 21, 180.00, 180.00, '03.02', 'cap03'),
  (9, 'Protecciones DC/AC (Sobretensiones, Diferenciales Clase A)', 1, 0, 380.00, 1.00, 380.00, 380.00, 380.00, 79.80, 459.80, 21, 380.00, 380.00, '03.03', 'cap03'),
  (10, 'Cableado solar 6mm y canalización reforzada', 1, 0, 250.00, 1.00, 250.00, 250.00, 250.00, 52.50, 302.50, 21, 250.00, 250.00, '03.04', 'cap03'),
  (11, 'Apertura de rozas y ayudas de albañilería', 1, 0, 450.00, 1.00, 450.00, 450.00, 450.00, 94.50, 544.50, 21, 450.00, 450.00, '04.01', 'cap04'),
  (12, 'Bancada de hormigón para unidad exterior (si procede)', 1, 0, 300.00, 1.00, 300.00, 300.00, 300.00, 63.00, 363.00, 21, 300.00, 300.00, '04.02', 'cap04')
) AS v(
  orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, codigo_visual, cap
) ON true
JOIN (
  SELECT id_linea, 'cap01' AS cap FROM cap01
  UNION ALL SELECT id_linea, 'cap02' AS cap FROM cap02
  UNION ALL SELECT id_linea, 'cap03' AS cap FROM cap03
  UNION ALL SELECT id_linea, 'cap04' AS cap FROM cap04
) c ON c.cap = v.cap;

-- Presupuestos asociados a intervenciones (seed)
WITH t AS (
  SELECT tc.id_tramite, c.id_cliente, l.id_local
  FROM tramites_contrato tc
  JOIN contratos c ON tc.id_contrato = c.id_contrato
  JOIN locales l ON c.id_local = l.id_local
  WHERE l.cups = 'ES0021000087654321AB2G'
    AND tc.tipo_tramite = 'Instalación'
  LIMIT 1
),
p AS (
  INSERT INTO presupuestos (
    cliente_id, vivienda_id, codigo_referencia, fecha,
    total, total_sin_iva, total_con_iva, estado, id_tramite
  )
  SELECT id_cliente, id_local, 'PRES-INT-002', CURRENT_DATE - 7,
         3872.00, 3200.00, 3872.00, 'Aceptado', id_tramite
  FROM t
  WHERE NOT EXISTS (SELECT 1 FROM presupuestos WHERE codigo_referencia = 'PRES-INT-002')
  RETURNING id_presupuesto
),
cap AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 1, 'INSTALACIÓN FV RESIDENCIAL', 'CAPITULO', '01' FROM p
  RETURNING id_linea
)
INSERT INTO presupuesto_lineas (
  presupuesto_id, orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, tipo_jerarquia, codigo_visual, padre_id
)
SELECT
  p.id_presupuesto, v.orden, v.concepto, v.cantidad, v.num_visitas, v.coste_unitario, v.factor_margen, v.total_coste, v.pvp_unitario, v.total_pvp,
  v.importe_iva, v.total_final, v.iva_porcentaje, v.precio_unitario, v.total_linea, 'PARTIDA', v.codigo_visual, cap.id_linea
FROM p
JOIN cap ON true
JOIN (VALUES
  (1, 'Suministro e instalación de 12 módulos 550W', 12, 0, 220.00, 1.00, 2640.00, 220.00, 2640.00, 554.40, 3194.40, 21, 220.00, 2640.00, '01.01'),
  (2, 'Inversor híbrido 6kW + protecciones', 1, 0, 560.00, 1.00, 560.00, 560.00, 560.00, 117.60, 677.60, 21, 560.00, 560.00, '01.02')
) AS v(
  orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, codigo_visual
) ON true;

WITH t AS (
  SELECT tc.id_tramite, c.id_cliente, l.id_local
  FROM tramites_contrato tc
  JOIN contratos c ON tc.id_contrato = c.id_contrato
  JOIN locales l ON c.id_local = l.id_local
  WHERE l.cups = 'ES0021000076543210AB3H'
    AND tc.tipo_tramite = 'Mantenimiento'
  LIMIT 1
),
p AS (
  INSERT INTO presupuestos (
    cliente_id, vivienda_id, codigo_referencia, fecha,
    total, total_sin_iva, total_con_iva, estado, id_tramite
  )
  SELECT id_cliente, id_local, 'PRES-INT-003', CURRENT_DATE - 5,
         1149.50, 950.00, 1149.50, 'Borrador', id_tramite
  FROM t
  WHERE NOT EXISTS (SELECT 1 FROM presupuestos WHERE codigo_referencia = 'PRES-INT-003')
  RETURNING id_presupuesto
),
cap AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 1, 'MANTENIMIENTO PROGRAMADO', 'CAPITULO', '01' FROM p
  RETURNING id_linea
)
INSERT INTO presupuesto_lineas (
  presupuesto_id, orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, tipo_jerarquia, codigo_visual, padre_id
)
SELECT
  p.id_presupuesto, v.orden, v.concepto, v.cantidad, v.num_visitas, v.coste_unitario, v.factor_margen, v.total_coste, v.pvp_unitario, v.total_pvp,
  v.importe_iva, v.total_final, v.iva_porcentaje, v.precio_unitario, v.total_linea, 'PARTIDA', v.codigo_visual, cap.id_linea
FROM p
JOIN cap ON true
JOIN (VALUES
  (1, 'Revisión anual de inversores', 1, 1, 500.00, 1.00, 500.00, 500.00, 500.00, 105.00, 605.00, 21, 500.00, 500.00, '01.01'),
  (2, 'Limpieza y termografía', 1, 1, 450.00, 1.00, 450.00, 450.00, 450.00, 94.50, 544.50, 21, 450.00, 450.00, '01.02')
) AS v(
  orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, codigo_visual
) ON true;

WITH t AS (
  SELECT tc.id_tramite, c.id_cliente, l.id_local
  FROM tramites_contrato tc
  JOIN contratos c ON tc.id_contrato = c.id_contrato
  JOIN locales l ON c.id_local = l.id_local
  WHERE l.cups = 'ES0021000065432109AB4I'
    AND tc.tipo_tramite = 'Ampliación'
  LIMIT 1
),
p AS (
  INSERT INTO presupuestos (
    cliente_id, vivienda_id, codigo_referencia, fecha,
    total, total_sin_iva, total_con_iva, estado, id_tramite
  )
  SELECT id_cliente, id_local, 'PRES-INT-004', CURRENT_DATE - 3,
         3388.00, 2800.00, 3388.00, 'Aceptado', id_tramite
  FROM t
  WHERE NOT EXISTS (SELECT 1 FROM presupuestos WHERE codigo_referencia = 'PRES-INT-004')
  RETURNING id_presupuesto
),
cap AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 1, 'AMPLIACIÓN DE SISTEMA', 'CAPITULO', '01' FROM p
  RETURNING id_linea
)
INSERT INTO presupuesto_lineas (
  presupuesto_id, orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, tipo_jerarquia, codigo_visual, padre_id
)
SELECT
  p.id_presupuesto, v.orden, v.concepto, v.cantidad, v.num_visitas, v.coste_unitario, v.factor_margen, v.total_coste, v.pvp_unitario, v.total_pvp,
  v.importe_iva, v.total_final, v.iva_porcentaje, v.precio_unitario, v.total_linea, 'PARTIDA', v.codigo_visual, cap.id_linea
FROM p
JOIN cap ON true
JOIN (VALUES
  (1, 'Ampliación de cuadro eléctrico', 1, 0, 1600.00, 1.00, 1600.00, 1600.00, 1600.00, 336.00, 1936.00, 21, 1600.00, 1600.00, '01.01'),
  (2, 'Instalación de 6 módulos adicionales', 6, 0, 200.00, 1.00, 1200.00, 200.00, 1200.00, 252.00, 1452.00, 21, 200.00, 1200.00, '01.02')
) AS v(
  orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, codigo_visual
) ON true;

-- ======================================================
-- 3.2 SEED PRESUPUESTO PREVENTIVO (FV)
-- ======================================================
WITH cliente AS (
  INSERT INTO clientes (
    nombre, apellido1, apellido2, dni,
    direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por
  ) VALUES (
    'Iberdrola', 'Renovables', 'S.A.U.', 'A-12345678',
    'Plaza Euskadi 5, Torre Iberdrola, 48009 Bilbao, España', '48009',
    'ES1221000418450200001234', 'Sistema'
  )
  ON CONFLICT (dni) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    apellido1 = EXCLUDED.apellido1,
    apellido2 = EXCLUDED.apellido2,
    direccion_fiscal_completa = EXCLUDED.direccion_fiscal_completa,
    codigo_postal = EXCLUDED.codigo_postal,
    cuenta_bancaria = EXCLUDED.cuenta_bancaria
  RETURNING id_cliente
),
local_ins AS (
  INSERT INTO locales (
    id_cliente, nombre_titular, apellido1_titular, apellido2_titular, dni_titular,
    cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por
  )
  SELECT
    id_cliente,
    'Iberdrola', 'Renovables', 'S.A.U.', 'A-12345678',
    'ES0031401234567890ABCD', '1234567VK4713S0001AB',
    'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla',
    37.331234, -5.858765, 'Sistema'
  FROM cliente
  WHERE NOT EXISTS (
    SELECT 1 FROM locales
    WHERE id_cliente = (SELECT id_cliente FROM cliente)
      AND direccion_completa = 'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla'
  )
  RETURNING id_local
),
local_sel AS (
  SELECT id_local FROM local_ins
  UNION ALL
  SELECT id_local FROM locales
  WHERE id_cliente = (SELECT id_cliente FROM cliente)
    AND direccion_completa = 'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla'
  LIMIT 1
),
pres AS (
  INSERT INTO presupuestos_preventivos (
    cliente_id, vivienda_id, fecha, estado, notas
  )
  SELECT
    (SELECT id_cliente FROM cliente),
    (SELECT id_local FROM local_sel),
    DATE '2026-02-04',
    'Aceptado',
    'Mantenimiento preventivo anual para planta FV 250 kWp: limpieza, termografía y revisión de inversores.'
  RETURNING id_presupuesto_prev
)
INSERT INTO presupuestos_preventivos_tareas (
  presupuesto_prev_id, nombre, descripcion, frecuencia_meses, orden, activo
)
SELECT p.id_presupuesto_prev, t.nombre, t.descripcion, t.frecuencia_meses, t.orden, t.activo
FROM pres p
CROSS JOIN (VALUES
  ('Limpieza de módulos FV', 'Limpieza en seco y verificación de sombras puntuales', 6, 1, true),
  ('Revisión de inversores', 'Chequeo de alarmas, rendimiento y firmware', 12, 2, true),
  ('Termografía de cuadros DC/AC', 'Detección de puntos calientes en conexiones', 12, 3, true),
  ('Inspección de estructura y anclajes', 'Par de apriete y corrosión', 12, 4, true),
  ('Verificación de protecciones', 'Comprobación de magnetotérmicos y fusibles', 6, 5, true),
  ('Revisión de monitorización', 'Validación de comunicaciones y datos SCADA', 3, 6, true)
) AS t(nombre, descripcion, frecuencia_meses, orden, activo);

-- ======================================================
-- 3.3 SEED PRESUPUESTO (TIPO PREVENTIVO)
-- ======================================================
WITH cliente AS (
  INSERT INTO clientes (
    nombre, apellido1, apellido2, dni,
    direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por
  ) VALUES (
    'Iberdrola', 'Renovables', 'S.A.U.', 'A-12345678',
    'Plaza Euskadi 5, Torre Iberdrola, 48009 Bilbao, España', '48009',
    'ES1221000418450200001234', 'Sistema'
  )
  ON CONFLICT (dni) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    apellido1 = EXCLUDED.apellido1,
    apellido2 = EXCLUDED.apellido2,
    direccion_fiscal_completa = EXCLUDED.direccion_fiscal_completa,
    codigo_postal = EXCLUDED.codigo_postal,
    cuenta_bancaria = EXCLUDED.cuenta_bancaria
  RETURNING id_cliente
),
local_ins AS (
  INSERT INTO locales (
    id_cliente, nombre_titular, apellido1_titular, apellido2_titular, dni_titular,
    cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por
  )
  SELECT
    id_cliente,
    'Iberdrola', 'Renovables', 'S.A.U.', 'A-12345678',
    'ES0031401234567890ABCD', '1234567VK4713S0001AB',
    'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla',
    37.331234, -5.858765, 'Sistema'
  FROM cliente
  WHERE NOT EXISTS (
    SELECT 1 FROM locales
    WHERE id_cliente = (SELECT id_cliente FROM cliente)
      AND direccion_completa = 'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla'
  )
  RETURNING id_local
),
local_sel AS (
  SELECT id_local FROM local_ins
  UNION ALL
  SELECT id_local FROM locales
  WHERE id_cliente = (SELECT id_cliente FROM cliente)
    AND direccion_completa = 'Parque Solar La Campiña, Km 12 A-92, 41500 Alcalá de Guadaíra, Sevilla'
  LIMIT 1
),
p AS (
  INSERT INTO presupuestos (
    cliente_id, vivienda_id, codigo_referencia, fecha,
    total, total_sin_iva, total_con_iva, estado, tipo_presupuesto
  )
  SELECT
    (SELECT id_cliente FROM cliente),
    (SELECT id_local FROM local_sel),
    'PRES-FV-MANT-001',
    DATE '2026-02-04',
    2274.80, 1880.00, 2274.80,
    'Aceptado', 'Preventivo'
  RETURNING id_presupuesto
),
cap AS (
  INSERT INTO presupuesto_lineas (presupuesto_id, orden, concepto, tipo_jerarquia, codigo_visual)
  SELECT id_presupuesto, 1, 'MANTENIMIENTO PREVENTIVO', 'CAPITULO', '01' FROM p
  RETURNING id_linea
)
INSERT INTO presupuesto_lineas (
  presupuesto_id, orden, concepto, cantidad, num_visitas, coste_unitario, factor_margen, total_coste, pvp_unitario, total_pvp,
  importe_iva, total_final, iva_porcentaje, precio_unitario, total_linea, tipo_jerarquia, codigo_visual, padre_id
)
VALUES
  ((SELECT id_presupuesto FROM p), 1, 'Limpieza de módulos FV', 1, 2, 400.00, 1.00, 400.00, 400.00, 400.00, 84.00, 484.00, 21, 400.00, 400.00, 'PARTIDA', '01.01', (SELECT id_linea FROM cap)),
  ((SELECT id_presupuesto FROM p), 2, 'Revisión de inversores', 1, 1, 350.00, 1.00, 350.00, 350.00, 350.00, 73.50, 423.50, 21, 350.00, 350.00, 'PARTIDA', '01.02', (SELECT id_linea FROM cap)),
  ((SELECT id_presupuesto FROM p), 3, 'Termografía de cuadros DC/AC', 1, 1, 500.00, 1.00, 500.00, 500.00, 500.00, 105.00, 605.00, 21, 500.00, 500.00, 'PARTIDA', '01.03', (SELECT id_linea FROM cap)),
  ((SELECT id_presupuesto FROM p), 4, 'Inspección de estructura y anclajes', 1, 1, 250.00, 1.00, 250.00, 250.00, 250.00, 52.50, 302.50, 21, 250.00, 250.00, 'PARTIDA', '01.04', (SELECT id_linea FROM cap)),
  ((SELECT id_presupuesto FROM p), 5, 'Verificación de protecciones', 1, 1, 200.00, 1.00, 200.00, 200.00, 200.00, 42.00, 242.00, 21, 200.00, 200.00, 'PARTIDA', '01.05', (SELECT id_linea FROM cap)),
  ((SELECT id_presupuesto FROM p), 6, 'Revisión de monitorización', 1, 1, 180.00, 1.00, 180.00, 180.00, 180.00, 37.80, 217.80, 21, 180.00, 180.00, 'PARTIDA', '01.06', (SELECT id_linea FROM cap));

-- ======================================================
-- 4. PERMISOS (Supabase)
-- ======================================================
DO $$
DECLARE
  target_role text := 'postgres';
BEGIN
  EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', target_role);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO %I', target_role);
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', target_role);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I', target_role);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO %I', target_role);
END $$;

-- ======================================================
-- 5. MODULO DE CHAT PROFESIONAL (STANDALONE & REALTIME)
-- ======================================================

-- Habilitar extensiones necesarias para UUIDs potentes
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Limpieza total para asegurar un estado consistente
DROP TABLE IF EXISTS public.chat_messages CASCADE;
DROP TABLE IF EXISTS public.chat_private_requests CASCADE;
DROP TABLE IF EXISTS public.chat_user_rooms CASCADE;
DROP TABLE IF EXISTS public.chat_rooms CASCADE;

-- 5.1 TABLA DE SALAS (ROOMS)
CREATE TABLE public.chat_rooms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  is_group BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID -- Identificador determinista generado por backend
);

-- 5.2 RELACIÓN USUARIO-SALA (MEMBRESÍAS)
CREATE TABLE public.chat_user_rooms (
  room_id UUID REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
  user_id UUID, -- Identificador determinista
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (room_id, user_id)
);

-- 5.3 TABLA DE MENSAJES (MESSAGES)
CREATE TABLE public.chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_id UUID REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
  sender_id UUID,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5.4 SEGURIDAD Y PERMISOS (Saneamiento)
CREATE TABLE public.chat_private_requests (
  id BIGSERIAL PRIMARY KEY,
  from_user_id UUID NOT NULL,
  to_user_id UUID NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  room_id UUID REFERENCES public.chat_rooms(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  responded_at TIMESTAMPTZ
);

-- 5.5 SEGURIDAD Y PERMISOS (Saneamiento)
-- Desactivamos RLS para esta fase; el backend gestiona la lógica de negocio.
ALTER TABLE public.chat_rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_user_rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_private_requests DISABLE ROW LEVEL SECURITY;

-- Permisos para que Supabase Realtime y el Frontend operen sin bloqueos
GRANT ALL ON TABLE public.chat_rooms TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.chat_user_rooms TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.chat_messages TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.chat_private_requests TO anon, authenticated, service_role;

-- 5.6 CONFIGURACIÓN SUPABASE REALTIME (PANTALLA COMPLETA)
-- Reiniciar la publicación para evitar errores de duplicados o tablas fantasmales
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR ALL TABLES;

-- Asegurar que las tablas tengan Replica Identity Full para actualizaciones precisas
ALTER TABLE public.chat_rooms REPLICA IDENTITY FULL;
ALTER TABLE public.chat_user_rooms REPLICA IDENTITY FULL;
ALTER TABLE public.chat_messages REPLICA IDENTITY FULL;
ALTER TABLE public.chat_private_requests REPLICA IDENTITY FULL;

-- Permisos extra para el rol anon (necesario para suscripciones directas)
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura anónima de mensajes" ON public.chat_messages FOR SELECT USING (true);
CREATE POLICY "Permitir inserción anónima de mensajes" ON public.chat_messages FOR INSERT WITH CHECK (true);
ALTER TABLE public.chat_messages DISABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------------------
-- ¡COPIAR Y PEGAR EN EL SQL EDITOR DE SUPABASE DESDE AQUÍ!
-- TABLAS PARA AREAS FUNCIONALES (Ficha Tecnica Local)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS areas_funcionales (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    orden INT,
    CONSTRAINT fk_area_func_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS area_funcional_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL,
    producto_id BIGINT,
    producto_texto VARCHAR(255),
    concepto VARCHAR(255),
    cantidad NUMERIC(12, 2),
    accion_requerida VARCHAR(255),
    orden INT,
    CONSTRAINT fk_af_linea_area FOREIGN KEY (id_area) REFERENCES areas_funcionales(id_area) ON DELETE CASCADE
);
-- -------------------------------------------------------------------------
-- FIN DEL BLOQUE PARA SUPABASE
-- -------------------------------------------------------------------------
-- 5.6 ÁREAS Y UBICACIONES FUNCIONALES (FICHA TÉCNICA - Ergonomía)
CREATE TABLE IF NOT EXISTS local_areas (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL REFERENCES locales(id_local) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    orden INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS local_ubicaciones (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL REFERENCES local_areas(id_area) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    orden INT DEFAULT 0
);

-- Asegurar que aparezcan en Realtime
ALTER TABLE public.local_areas REPLICA IDENTITY FULL;
ALTER TABLE public.local_ubicaciones REPLICA IDENTITY FULL;

--------------------------------------------------------------------------------------------------------------------------------------
-- FIX PARA SUPABASE: Actualizar tipo de columna fecha_aceptacion de DATE a TIMESTAMPTZ para coincidir con backend Java (OffsetDateTime)
--------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE presupuestos ALTER COLUMN fecha_aceptacion TYPE TIMESTAMPTZ USING fecha_aceptacion::TIMESTAMPTZ;

-- -------------------------------------------------------------------------
-- FIX PARA PRODUCTOS: Añadir margen e iva para desglose de precios profesional
-- -------------------------------------------------------------------------
ALTER TABLE productos ADD COLUMN IF NOT EXISTS margen NUMERIC(5, 2) DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS iva NUMERIC(5, 2) DEFAULT 21;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_venta NUMERIC(12, 2) DEFAULT 0;

-- -------------------------------------------------------------------------
-- FIX PARA SEGUIMIENTO: Añadir es_urgente e id_proveedor si no existen
-- -------------------------------------------------------------------------
ALTER TABLE SEGUIMIENTO_TRAMITES ADD COLUMN IF NOT EXISTS es_urgente BOOLEAN DEFAULT FALSE;
ALTER TABLE SEGUIMIENTO_TRAMITES ADD COLUMN IF NOT EXISTS id_proveedor BIGINT;
ALTER TABLE SEGUIMIENTO_TRAMITES ADD COLUMN IF NOT EXISTS id_creador BIGINT; -- Añadido por si acaso

-- -------------------------------------------------------------------------
-- FIX PARA TRAMITES: Asegurar que es_urgente existe
-- -------------------------------------------------------------------------
ALTER TABLE TRAMITES_CONTRATO ADD COLUMN IF NOT EXISTS es_urgente BOOLEAN DEFAULT FALSE;
-- -------------------------------------------------------------------------
-- MODULO PROVEEDORES: Albaranes y Facturas
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS albaranes_proveedor (
    id_albaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    numero_albaran VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    id_tramite BIGINT NULL,
    notas TEXT,
    CONSTRAINT fk_alb_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    CONSTRAINT fk_alb_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS albaranes_venta (
    id_albaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL,
    id_tramite BIGINT NULL,
    numero_albaran VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    notas TEXT,
    CONSTRAINT fk_alb_venta_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    CONSTRAINT fk_alb_venta_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_alb_venta_presupuesto ON albaranes_venta(presupuesto_id);

-- Regla de negocio: albarán de venta siempre ligado a presupuesto aceptado.
-- Si existen filas legacy con presupuesto_id NULL, corregirlas/eliminarlas antes de aplicar SET NOT NULL.
ALTER TABLE IF EXISTS albaranes_venta
    ALTER COLUMN presupuesto_id SET NOT NULL;

CREATE TABLE IF NOT EXISTS albaranes_venta_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albaran_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2) DEFAULT 0,
    precio_unitario NUMERIC(12, 2) DEFAULT 0,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    total_linea NUMERIC(12, 2) DEFAULT 0,
    total_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    CONSTRAINT fk_alb_venta_linea_albaran FOREIGN KEY (albaran_id) REFERENCES albaranes_venta(id_albaran) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_alb_venta_lineas_albaran ON albaranes_venta_lineas(albaran_id);

CREATE TABLE IF NOT EXISTS facturas_venta (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL,
    id_tramite BIGINT NULL,
    numero_factura VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Emitida',
    notas TEXT,
    CONSTRAINT fk_fac_venta_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    CONSTRAINT fk_fac_venta_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fac_venta_presupuesto ON facturas_venta(presupuesto_id);

CREATE TABLE IF NOT EXISTS albaranes_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albaran_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2) DEFAULT 0,
    precio_unitario NUMERIC(12, 2) DEFAULT 0,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    total_linea NUMERIC(12, 2) DEFAULT 0,
    total_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    CONSTRAINT fk_alb_prov_linea_albaran FOREIGN KEY (albaran_id) REFERENCES albaranes_proveedor(id_albaran) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_alb_prov_lineas_albaran ON albaranes_proveedor_lineas(albaran_id);

CREATE TABLE IF NOT EXISTS facturas_proveedor (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    numero_factura VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Pendiente', -- Pendiente, Pagada, Vencida
    id_tramite BIGINT NULL,
    notas TEXT,
    CONSTRAINT fk_fac_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    CONSTRAINT fk_fac_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS facturas_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2) DEFAULT 0,
    precio_unitario NUMERIC(12, 2) DEFAULT 0,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    total_linea NUMERIC(12, 2) DEFAULT 0,
    total_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    CONSTRAINT fk_fac_prov_linea_factura FOREIGN KEY (factura_id) REFERENCES facturas_proveedor(id_factura) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fac_prov_lineas_factura ON facturas_proveedor_lineas(factura_id);

-- ======================================================
-- 7. GESTOR DOCUMENTAL (Metadatos)
-- ======================================================
CREATE TABLE IF NOT EXISTS archivos_adjuntos (
    id_archivo UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    entidad_tipo VARCHAR(50) NOT NULL,
    entidad_id BIGINT NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_disco VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(120),
    tamano_bytes BIGINT,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archivos_adjuntos_entidad ON archivos_adjuntos(entidad_tipo, entidad_id);

-- ======================================================
-- 6. DATOS DE PRUEBA Y RESTAURACIÓN
-- ======================================================

-- 6.1 Asegurar esquema antes de insertar
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS email VARCHAR(100);
ALTER TABLE albaranes_proveedor ADD COLUMN IF NOT EXISTS factura_id BIGINT REFERENCES facturas_proveedor(id_factura) ON DELETE SET NULL;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS estado VARCHAR(50) DEFAULT 'Activo';
ALTER TABLE locales ADD COLUMN IF NOT EXISTS referencia_catastral VARCHAR(20);
ALTER TABLE locales ALTER COLUMN referencia_catastral SET NOT NULL;
ALTER TABLE locales DROP CONSTRAINT IF EXISTS uq_referencia_catastral;
ALTER TABLE locales ADD CONSTRAINT uq_referencia_catastral UNIQUE (referencia_catastral);
ALTER TABLE locales ALTER COLUMN id_cliente DROP NOT NULL;

-- 6.2 Limpieza de tablas (Orden de dependencias)
-- TRUNCATE TABLE 
--     presupuesto_lineas, 
--     presupuestos, 
--     seguimiento_tramites, 
--     tramites_contrato, 
--     contratos, 
--     locales, 
--     clientes, 
--     proveedor_contactos, 
--     proveedor_oficios, 
--     proveedores, 
--     productos, 
--     usuarios 
-- RESTART IDENTITY CASCADE;

-- 6.2 Usuarios (BCrypt)
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) VALUES 
('jefe_admin', '$2a$10$fx8sccd3svi33CcKUrH.BOfPEiC8Y.qWD1rYKkobZ2rporK45MmGi', 'ADMIN', 'jefeadmin@insene.com'),
('carlos_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'carlos.tec@insene.com'),
('marta_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'marta.tec@insene.com'),
('raul_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'raul.tec@insene.com'),
('elena_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'elena.tec@insene.com'),
('pablo_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'pablo.tec@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- 6.3 Clientes (11 Clientes base)
INSERT INTO clientes (nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
SELECT * FROM (VALUES
    ('Jose', 'Brenes', 'Oliva', '75892994D', 'Calle Mina 4, Arahal', '41600', 'ES1234567890123456789012', 'jefe_admin'),
    ('Ana', 'García', 'López', '12345678Z', 'Avda. Constitución 12, Sevilla', '41001', 'ES9876543210987654321098', 'jefe_admin'),
    ('Manuel', 'Sánchez', 'Pérez', '23456789X', 'Calle Real 45, Alcalá de Guadaíra', '41500', 'ES8765432109876543210987', 'jefe_admin'),
    ('María', 'Rodríguez', 'Ruiz', '34567890C', 'Plaza Mayor 1, Dos Hermanas', '41700', 'ES7654321098765432109876', 'jefe_admin'),
    ('David', 'Martínez', 'Jiménez', '45678901V', 'Calle Betis 8, Sevilla', '41010', 'ES6543210987654321098765', 'jefe_admin'),
    ('Lucía', 'Hernández', 'Muñoz', '56789012B', 'Calle Larga 22, Arahal', '41600', 'ES5432109876543210987654', 'jefe_admin'),
    ('Javier', 'Díaz', 'Moreno', '67890123N', 'Calle Ancha 15, Paradas', '41610', 'ES4321098765432109876543', 'jefe_admin'),
    ('Elena', 'Álvarez', 'Serrano', '78901234M', 'Calle Sierpes 3, Sevilla', '41004', 'ES3210987654321098765432', 'jefe_admin'),
    ('Pablo', 'Romero', 'Navarro', '89012345Q', 'Calle Nueva 10, Marchena', '41620', 'ES2109876543210987654321', 'jefe_admin'),
    ('Marta', 'Torres', 'Castro', '90123456W', 'Calle Feria 55, Sevilla', '41003', 'ES1098765432109876543210', 'jefe_admin'),
    ('Antonio', 'Vázquez', 'Blanco', '01234567E', 'Calle Pureza 2, Sevilla', '41011', 'ES0987654321098765432109', 'jefe_admin')
) AS v(nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
WHERE NOT EXISTS (SELECT 1 FROM clientes c WHERE c.dni = v.dni);

-- 6.4 Locales asociados
INSERT INTO locales (id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
SELECT * FROM (VALUES
    (1, 'Jose', 'Brenes', '75892994D', 'ES0021000012345678AB1F', '1234567TG8901S0001FF', 'Calle Mina 4, Arahal', 37.2628, -5.4772, 'jefe_admin'),
    (2, 'Ana', 'García', '12345678Z', 'ES0021000087654321AB2G', '0869501QA5406N0003HI', 'Calle Diputación 250, Barcelona', 41.3887, 2.1645, 'jefe_admin'),
    (3, 'Manuel', 'Sánchez', '23456789X', 'ES0021000076543210AB3H', '6029215TF7760G0001AK', 'Avda. Los Majuelos 30, S.C. Tenerife', 28.4550, -16.2941, 'jefe_admin'),
    (10, 'Marta', 'Torres', '90123456W', 'ES0021000009876543AB0O', '0165203TG4106N0001PH', 'Calle Feria 12, Sevilla', 37.3977, -5.9922, 'jefe_admin')
) AS v(id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
WHERE NOT EXISTS (SELECT 1 FROM locales l WHERE l.direccion_completa = v.direccion_completa);

-- 6.5 Contratos base
INSERT INTO contratos (id_cliente, id_local, fecha_inicio, fecha_vencimiento, tipo_contrato, creado_por, estado)
SELECT * FROM (VALUES
    (1, 1, '2025-01-01'::date, '2026-01-01'::date, 'Instalación', 'jefe_admin', 'Activo'),
    (2, 2, '2025-02-01'::date, '2026-02-01'::date, 'Instalación', 'jefe_admin', 'Activo'),
    (3, 3, '2025-02-15'::date, '2026-02-15'::date, 'Preventivo', 'jefe_admin', 'Activo'),
    (10, 10, '2025-06-01'::date, '2026-06-01'::date, 'Ampliación', 'jefe_admin', 'Activo')
) AS v(id_cliente, id_local, fecha_inicio, fecha_vencimiento, tipo_contrato, creado_por, estado)
WHERE NOT EXISTS (SELECT 1 FROM contratos c WHERE c.id_cliente = v.id_cliente AND c.id_local = v.id_local AND c.fecha_inicio = v.fecha_inicio);

-- 6.6 NUEVAS TABLAS PARA TÉCNICOS INSTALADORES Y ASIGNACIÓN MÚLTIPLE
CREATE TABLE IF NOT EXISTS tecnicos_instaladores (
    id_tecnico_instalador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seguimiento_instaladores (
    id_seguimiento BIGINT NOT NULL,
    id_tecnico_instalador BIGINT NOT NULL,
    PRIMARY KEY (id_seguimiento, id_tecnico_instalador),
    CONSTRAINT fk_si_seguimiento FOREIGN KEY (id_seguimiento) REFERENCES SEGUIMIENTO_TRAMITES(id_seguimiento) ON DELETE CASCADE,
    CONSTRAINT fk_si_instalador FOREIGN KEY (id_tecnico_instalador) REFERENCES tecnicos_instaladores(id_tecnico_instalador) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seguimiento_tecnicos (
    id_seguimiento BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    PRIMARY KEY (id_seguimiento, id_usuario),
    CONSTRAINT fk_st_seguimiento FOREIGN KEY (id_seguimiento) REFERENCES SEGUIMIENTO_TRAMITES(id_seguimiento) ON DELETE CASCADE,
    CONSTRAINT fk_st_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- Datos de prueba para técnicos instaladores
INSERT INTO tecnicos_instaladores (nombre, telefono, activo) VALUES
('Juan Pérez', '600111222', TRUE),
('Andrés García', '600333444', TRUE),
('Luis Rodríguez', '600555666', FALSE)
ON CONFLICT (nombre) DO NOTHING;

