-- ======================================================
-- 1. INICIALIZACIÓN (Extensiones y Esquemas)
-- ======================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS auth;

-- ======================================================
-- 2. ENUMS
-- ======================================================
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employee_status') THEN CREATE TYPE employee_status AS ENUM ('ACTIVO', 'INACTIVO'); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'absence_type') THEN CREATE TYPE absence_type AS ENUM ('VACACIONES', 'BAJA_MEDICA', 'ASUNTOS_PROPIOS'); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'absence_status') THEN CREATE TYPE absence_status AS ENUM ('PENDIENTE', 'APROBADA', 'RECHAZADA'); END IF; END $$;

-- ======================================================
-- 3. TABLAS NIVEL 1 (Maestras / Independientes)
-- ======================================================

-- 3.1 USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(50) DEFAULT 'LECTURA',
    email VARCHAR(100),
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3.2 CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido1 VARCHAR(50) NOT NULL,
    apellido2 VARCHAR(50),
    dni VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100),
    descripcion VARCHAR(255),
    direccion_fiscal_completa VARCHAR(255),
    codigo_postal VARCHAR(10),
    cuenta_bancaria VARCHAR(34),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL
);

-- 3.3 PROVEEDORES
CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR(100) NOT NULL,
    razon_social VARCHAR(100),
    es_autonomo BOOLEAN DEFAULT FALSE,
    cif VARCHAR(20) NOT NULL,
    direccion_fiscal VARCHAR(255),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema'
);

-- 3.4 PRODUCTOS
CREATE TABLE IF NOT EXISTS productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_ref_producto VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL,
    coste NUMERIC(12, 2) NOT NULL,
    margen NUMERIC(5, 2) DEFAULT 0,
    iva NUMERIC(5, 2) DEFAULT 21,
    precio_venta NUMERIC(12, 2) DEFAULT 0,
    categoria VARCHAR(100)
);

-- 3.5 TÉCNICOS INSTALADORES
CREATE TABLE IF NOT EXISTS tecnicos_instaladores (
    id_tecnico_instalador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3.6 CHAT SALAS (ROOMS)
CREATE TABLE IF NOT EXISTS chat_rooms (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    is_group BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID
);

-- 3.7 AUDITORIA SISTEMA
CREATE TABLE IF NOT EXISTS auditoria_sistema (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(50) NOT NULL,
    id_registro BIGINT NOT NULL,
    campo_modificado VARCHAR(50),
    valor_anterior TEXT,
    valor_nuevo TEXT,
    fecha_cambio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_bd VARCHAR(100)
);

-- ======================================================
-- 4. TABLAS NIVEL 2 (Una dependencia)
-- ======================================================

-- 4.1 LOCALES (Depende de Clientes)
CREATE TABLE IF NOT EXISTS locales (
    id_local BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NULL,
    nombre_titular VARCHAR(50) NOT NULL,
    apellido1_titular VARCHAR(50) NOT NULL,
    apellido2_titular VARCHAR(50),
    dni_titular VARCHAR(15),
    cups VARCHAR(22) NULL,
    referencia_catastral VARCHAR(20) NOT NULL UNIQUE,
    direccion_completa VARCHAR(255) NOT NULL,
    latitud DECIMAL(10, 8) NULL,
    longitud DECIMAL(11, 8) NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    CONSTRAINT fk_local_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 4.2 EMPLEADOS (Depende de Auth.Users)
CREATE TABLE IF NOT EXISTS empleados (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    nombre_completo TEXT NOT NULL,
    dni_nie TEXT UNIQUE NOT NULL,
    fecha_alta DATE NOT NULL,
    fecha_baja DATE,
    puesto TEXT,
    estado employee_status DEFAULT 'ACTIVO' NOT NULL
);

-- 4.3 CONTACTOS Y OFICIOS DE PROVEEDORES
CREATE TABLE IF NOT EXISTS proveedor_oficios (
    id_oficio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    oficio VARCHAR(100) NOT NULL,
    CONSTRAINT fk_oficio_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS proveedor_contactos (
    id_contacto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cargo VARCHAR(255),
    telefono VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT fk_contacto_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE
);

-- 4.4 TELÉFONOS DE CLIENTES
CREATE TABLE IF NOT EXISTS cliente_telefonos (
    id_telefono BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    descripcion VARCHAR(50),
    CONSTRAINT fk_tel_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- 4.5 CONTRATOS (Depende de Clientes y Locales)
CREATE TABLE IF NOT EXISTS contratos (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_local BIGINT NOT NULL,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(50) NOT NULL,
    ce_previo VARCHAR(50) DEFAULT 'Pendiente',
    ce_post VARCHAR(50) DEFAULT 'Pendiente',
    enviado_cee_post BOOLEAN DEFAULT FALSE,
    licencia_obras VARCHAR(50) DEFAULT 'No requerida',
    mtd BOOLEAN DEFAULT FALSE,
    planos BOOLEAN DEFAULT FALSE,
    subvencion_estado VARCHAR(50) DEFAULT 'No solicitada',
    libro_edif_incluido BOOLEAN DEFAULT FALSE,
    observaciones TEXT NULL,
    estado VARCHAR(50) DEFAULT 'Activo',
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100) NULL,
    fecha_modificacion TIMESTAMPTZ NULL,
    id_presupuesto_origen BIGINT NULL,
    forma_pago VARCHAR(100),
    nombre_financiera VARCHAR(100),
    fecha_inicio_financiacion DATE,
    importe_cuota NUMERIC(12, 2),
    importe_total_financiado NUMERIC(12, 2),
    porcentaje_contado NUMERIC(5, 2),
    CONSTRAINT fk_contrato_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_contrato_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE,
    CONSTRAINT chk_periodo_contrato CHECK (fecha_vencimiento >= fecha_inicio)
);

-- ======================================================
-- 5. TABLAS NIVEL 3 (Complejas / Múltiples dependencias)
-- ======================================================

-- 5.1 ÁREAS Y UBICACIONES (Ficha Técnica Local)
CREATE TABLE IF NOT EXISTS local_areas (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    orden INTEGER DEFAULT 0,
    CONSTRAINT fk_area_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS local_ubicaciones (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    orden INTEGER DEFAULT 0,
    CONSTRAINT fk_ubicacion_area FOREIGN KEY (id_area) REFERENCES local_areas(id_area) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS areas_funcionales (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    orden INT,
    CONSTRAINT fk_area_func_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS area_funcional_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL,
    producto_id BIGINT,
    producto_texto VARCHAR(255),
    concepto VARCHAR(255),
    cantidad NUMERIC(12, 2),
    accion_requerida VARCHAR(255),
    orden INT,
    CONSTRAINT fk_af_linea_area FOREIGN KEY (id_area) REFERENCES areas_funcionales(id_area) ON DELETE CASCADE
);

-- 5.2 TRÁMITES E INTERVENCIONES
CREATE TABLE IF NOT EXISTS TRAMITES_CONTRATO (
    id_tramite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato BIGINT NOT NULL,
    tipo_tramite VARCHAR(255) NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    tecnico_asignado VARCHAR(255) NULL,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    facturado BOOLEAN DEFAULT FALSE,
    descripcion TEXT NULL,
    detalle_seguimiento TEXT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion TIMESTAMPTZ NULL,
    id_tramite_bloqueante BIGINT NULL,
    CONSTRAINT fk_tramite_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) ON DELETE CASCADE,
    CONSTRAINT fk_tramite_bloqueante FOREIGN KEY (id_tramite_bloqueante) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

-- 5.3 PRESUPUESTOS (Unificado)
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2) DEFAULT 0,
    total_sin_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Borrador',
    tipo_presupuesto VARCHAR(20) DEFAULT 'Obra',
    descripcion TEXT NULL,
    id_tramite BIGINT NULL,
    fecha_aceptacion TIMESTAMPTZ NULL,
    dias_validez INT NULL,
    id_contrato BIGINT NULL,
    CONSTRAINT fk_presupuesto_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local) ON DELETE RESTRICT,
    CONSTRAINT fk_presupuesto_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE SET NULL,
    CONSTRAINT fk_presupuesto_contrato FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL,
    orden INT NOT NULL,
    producto_id BIGINT NULL,
    producto_texto VARCHAR(255) NULL,
    concepto VARCHAR(255) NOT NULL,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    coste_unitario NUMERIC(12, 2),
    factor_margen NUMERIC(6, 2) DEFAULT 1.00,
    total_coste NUMERIC(12, 2),
    pvp_unitario NUMERIC(12, 2),
    total_pvp NUMERIC(12, 2),
    importe_iva NUMERIC(12, 2),
    total_final NUMERIC(12, 2),
    total_linea NUMERIC(12, 2),
    tipo_jerarquia VARCHAR(20) DEFAULT 'PARTIDA',
    codigo_visual VARCHAR(20),
    padre_id BIGINT NULL,
    num_visitas INT DEFAULT 0,
    CONSTRAINT fk_linea_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    CONSTRAINT fk_presupuesto_lineas_padre FOREIGN KEY (padre_id) REFERENCES presupuesto_lineas(id_linea) ON DELETE CASCADE
);

-- 5.4 SEGUIMIENTO Y ASIGNACIONES
CREATE TABLE IF NOT EXISTS SEGUIMIENTO_TRAMITES (
    id_seguimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_creador BIGINT NOT NULL,
    id_proveedor BIGINT NULL,
    comentario TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_seguimiento DATE NULL,
    es_urgente BOOLEAN DEFAULT FALSE,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    CONSTRAINT fk_seg_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE CASCADE,
    CONSTRAINT fk_seg_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_creador FOREIGN KEY (id_creador) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_seg_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tramite_instaladores (
    id_tramite BIGINT NOT NULL,
    id_tecnico_instalador BIGINT NOT NULL,
    PRIMARY KEY (id_tramite, id_tecnico_instalador),
    CONSTRAINT fk_ti_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE CASCADE,
    CONSTRAINT fk_ti_instalador FOREIGN KEY (id_tecnico_instalador) REFERENCES tecnicos_instaladores(id_tecnico_instalador) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seguimiento_instaladores (
    id_seguimiento BIGINT NOT NULL,
    id_tecnico_instalador BIGINT NOT NULL,
    PRIMARY KEY (id_seguimiento, id_tecnico_instalador),
    CONSTRAINT fk_si_seguimiento FOREIGN KEY (id_seguimiento) REFERENCES SEGUIMIENTO_TRAMITES(id_seguimiento) ON DELETE CASCADE,
    CONSTRAINT fk_si_instalador FOREIGN KEY (id_tecnico_instalador) REFERENCES tecnicos_instaladores(id_tecnico_instalador) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seguimiento_tecnicos (
    id_seguimiento BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    PRIMARY KEY (id_seguimiento, id_usuario),
    CONSTRAINT fk_st_seguimiento FOREIGN KEY (id_seguimiento) REFERENCES SEGUIMIENTO_TRAMITES(id_seguimiento) ON DELETE CASCADE,
    CONSTRAINT fk_st_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- 5.5 AUDITORÍA Y SESIONES
CREATE TABLE IF NOT EXISTS auditoria_sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    nombre_usuario VARCHAR(50) NOT NULL,
    fecha_inicio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMPTZ NULL,
    fecha_ultima_actividad TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ip_acceso VARCHAR(45),
    estado VARCHAR(20) DEFAULT 'Conectado',
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- 5.6 GESTOR DOCUMENTAL
CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    file_name_original VARCHAR(255) NOT NULL,
    file_name_system VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_type VARCHAR(255),
    size BIGINT,
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS archivos_cliente (
    id_archivo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    categoria VARCHAR(100) DEFAULT 'Otros',
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS archivos_tramite (
    id_archivo_t BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite BIGINT NOT NULL,
    nombre_visible VARCHAR(255) NOT NULL,
    nombre_fisico VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100),
    fecha_subida TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(50),
    CONSTRAINT fk_arch_tramite FOREIGN KEY (id_tramite) REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS archivos_adjuntos (
    id_archivo UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    entidad_tipo VARCHAR(50) NOT NULL,
    entidad_id BIGINT NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_disco VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(120),
    tamano_bytes BIGINT,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5.7 NOTIFICACIONES
CREATE TABLE IF NOT EXISTS notificaciones (
    id_notificacion BIGSERIAL PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES USUARIOS(id_usuario) ON DELETE CASCADE,
    mensaje TEXT NOT NULL,
    link TEXT,
    leida BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5.8 CHAT Y MENSAJERÍA
CREATE TABLE IF NOT EXISTS chat_user_rooms (
    room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
    user_id UUID,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id UUID,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_private_requests (
    id BIGSERIAL PRIMARY KEY,
    from_user_id UUID NOT NULL,
    to_user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    room_id UUID REFERENCES chat_rooms(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    responded_at TIMESTAMPTZ
);

-- 5.9 RRHH Y CONTROL HORARIO
CREATE TABLE IF NOT EXISTS saldos_vacaciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empleado_id UUID NOT NULL REFERENCES empleados(id) ON DELETE CASCADE,
    anio INT NOT NULL,
    dias_totales INT NOT NULL,
    dias_disfrutados INT DEFAULT 0 NOT NULL,
    UNIQUE(empleado_id, anio)
);

CREATE TABLE IF NOT EXISTS ausencias (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empleado_id UUID NOT NULL REFERENCES empleados(id) ON DELETE CASCADE,
    tipo absence_type NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    dias_solicitados INT NOT NULL,
    estado absence_status DEFAULT 'PENDIENTE' NOT NULL,
    solicitado_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS fichajes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empleado_id UUID NOT NULL REFERENCES empleados(id) ON DELETE CASCADE,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_entrada TIME NOT NULL,
    hora_salida TIME,
    minutos_pausa INT DEFAULT 0,
    estado VARCHAR(20) CHECK (estado IN ('TRABAJANDO', 'EN_PAUSA', 'FINALIZADO')) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_fichaje_dia UNIQUE (empleado_id, fecha)
);

-- 5.10 DOCUMENTOS COMERCIALES (Albaranes y Facturas)
CREATE TABLE IF NOT EXISTS albaranes_proveedor (
    id_albaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    numero_albaran VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    id_tramite BIGINT NULL,
    notas TEXT,
    factura_id BIGINT NULL,
    CONSTRAINT fk_alb_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    CONSTRAINT fk_alb_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS albaranes_venta (
    id_albaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NULL,
    id_tramite BIGINT NULL,
    numero_albaran VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    notas TEXT,
    CONSTRAINT fk_alb_venta_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE SET NULL,
    CONSTRAINT fk_alb_venta_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS facturas_proveedor (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL,
    numero_factura VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Pendiente',
    id_tramite BIGINT NULL,
    notas TEXT,
    CONSTRAINT fk_fac_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor) ON DELETE CASCADE,
    CONSTRAINT fk_fac_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS facturas_venta (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NULL,
    id_tramite BIGINT NULL,
    numero_factura VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Emitida',
    notas TEXT,
    CONSTRAINT fk_fac_venta_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto) ON DELETE SET NULL,
    CONSTRAINT fk_fac_venta_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

-- 5.11 LEGALIZACIONES Y MANTENIMIENTO
CREATE TABLE IF NOT EXISTS legalizaciones_bt (
    id_legalizacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL,
    id_tramite BIGINT,
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_legalizacion DATE,
    datos_json TEXT,
    estado VARCHAR(50) DEFAULT 'Pendiente',
    CONSTRAINT fk_leg_local FOREIGN KEY (id_local) REFERENCES locales(id_local) ON DELETE CASCADE,
    CONSTRAINT fk_leg_tramite FOREIGN KEY (id_tramite) REFERENCES TRAMITES_CONTRATO(id_tramite) ON DELETE SET NULL
);

-- ======================================================
-- 6. VISTAS
-- ======================================================
CREATE OR REPLACE VIEW vista_estado_contratos AS
SELECT
    c.id_contrato,
    cl.id_cliente,
    cl.dni as dni_cliente,
    CONCAT(cl.apellido1, ' ', COALESCE(cl.apellido2, ''), ' , ', cl.nombre) AS nombre_cliente,
    l.direccion_completa,
    c.tipo_contrato,
    c.fecha_alta,
    c.fecha_vencimiento,
    CASE
        WHEN c.fecha_vencimiento < CURRENT_DATE THEN 'VENCIDO'
        ELSE 'ACTIVO'
    END AS estado
FROM contratos c
JOIN clientes cl ON c.id_cliente = cl.id_cliente
JOIN locales l ON c.id_local = l.id_local;

-- ======================================================
-- 7. CONSTRAINTS ADICIONALES E INDICES
-- ======================================================
ALTER TABLE contratos ADD CONSTRAINT fk_contrato_presupuesto_origen FOREIGN KEY (id_presupuesto_origen) REFERENCES presupuestos(id_presupuesto) ON DELETE SET NULL;
ALTER TABLE albaranes_proveedor ADD CONSTRAINT fk_alb_factura_asoc FOREIGN KEY (factura_id) REFERENCES facturas_proveedor(id_factura) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_crm_docs_ref ON crm_documents(entity_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_presupuestos_tramite ON presupuestos(id_tramite);
CREATE INDEX IF NOT EXISTS idx_tramite_instaladores_tramite ON tramite_instaladores(id_tramite);

-- ======================================================
-- 8. DATOS INICIALES (INSERTS)
-- ======================================================

-- 8.1 USUARIOS (BCrypt)
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) VALUES 
('jefe_admin', '$2a$10$fx8sccd3svi33CcKUrH.BOfPEiC8Y.qWD1rYKkobZ2rporK45MmGi', 'ADMIN', 'jefeadmin@insene.com'),
('carlos_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'carlos.tec@insene.com'),
('marta_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'marta.tec@insene.com'),
('raul_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'raul.tec@insene.com'),
('elena_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'elena.tec@insene.com'),
('pablo_tec', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'TÉCNICO', 'pablo.tec@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- 8.2 CLIENTES
INSERT INTO clientes (nombre, apellido1, apellido2, dni, direccion_fiscal_completa, codigo_postal, cuenta_bancaria, creado_por)
SELECT * FROM (VALUES
    ('Jose', 'Brenes', 'Oliva', '75892994D', 'Calle Mina 4, Arahal', '41600', 'ES1234567890123456789012', 'jefe_admin'),
    ('Ana', 'García', 'López', '12345678Z', 'Avda. Constitución 12, Sevilla', '41001', 'ES9876543210987654321098', 'jefe_admin'),
    ('Manuel', 'Sánchez', 'Pérez', '23456789X', 'Calle Real 45, Alcalá de Guadaíra', '41500', 'ES8765432109876543210987', 'jefe_admin'),
    ('María', 'Rodríguez', 'Ruiz', '34567890C', 'Plaza Mayor 1, Dos Hermanas', '41700', 'ES7654321098765432109876', 'jefe_admin'),
    ('David', 'Martínez', 'Jiménez', '45678901V', 'Calle Betis 8, Sevilla', '41010', 'ES6543210987654321098765', 'jefe_admin'),
    ('Lucía', 'Hernández', 'Muñoz', '56789012B', 'Calle Larga 22, Arahal', '41600', 'ES5432109876543210987654', 'jefe_admin'),
    ('Javier', 'Díaz', 'Moreno', '67890123N', 'Calle Ancha 15, Paradas', '41610', 'ES4321098765432109876543', 'jefe_admin'),
    ('Elena', 'Álvarez', 'Serrano', '78901234M', 'Calle Sierpes 3, Sevilla', '41004', 'ES3210987654321098765432', 'jefe_admin'),
    ('Pablo', 'Romero', 'Navarro', '89012345Q', 'Calle Nueva 10, Marchena', '41620', 'ES2109876543210987654321', 'jefe_admin'),
    ('Marta', 'Torres', 'Castro', '90123456W', 'Calle Feria 55, Sevilla', '41003', 'ES1098765432109876543210', 'jefe_admin'),
    ('Antonio', 'Vázquez', 'Blanco', '01234567E', 'Calle Pureza 2, Sevilla', '41011', 'ES0987654321098765432109', 'jefe_admin')
) AS v(nombre, apellido1, apellido2, dni, direccion, cp, cuenta, creador)
WHERE NOT EXISTS (SELECT 1 FROM clientes c WHERE c.dni = v.dni);

-- 8.3 LOCALES
INSERT INTO locales (id_cliente, nombre_titular, apellido1_titular, dni_titular, cups, referencia_catastral, direccion_completa, latitud, longitud, creado_por)
SELECT * FROM (VALUES
    (1, 'Jose', 'Brenes', '75892994D', 'ES0021000012345678AB1F', '1234567TG8901S0001FF', 'Calle Mina 4, Arahal', 37.2628, -5.4772, 'jefe_admin'),
    (2, 'Ana', 'García', '12345678Z', 'ES0021000087654321AB2G', '0869501QA5406N0003HI', 'Calle Diputación 250, Barcelona', 41.3887, 2.1645, 'jefe_admin'),
    (3, 'Manuel', 'Sánchez', '23456789X', 'ES0021000076543210AB3H', '6029215TF7760G0001AK', 'Avda. Los Majuelos 30, S.C. Tenerife', 28.4550, -16.2941, 'jefe_admin'),
    (10, 'Marta', 'Torres', '90123456W', 'ES0021000009876543AB0O', '0165203TG4106N0001PH', 'Calle Feria 12, Sevilla', 37.3977, -5.9922, 'jefe_admin')
) AS v(id_cliente, nombre, apellido, dni, cups, ref_cat, direccion, lat, lon, creador)
WHERE NOT EXISTS (SELECT 1 FROM locales l WHERE l.cups = v.cups);

-- 8.4 PRODUCTOS
INSERT INTO productos (cod_ref_producto, descripcion, coste, categoria) VALUES
('PNL-JKM550', 'Panel Solar Jinko Tiger Neo 550W Monocristalino', 145.50, 'Paneles Solares'),
('PNL-CS600', 'Panel Canadian Solar 600W HiKu6', 162.00, 'Paneles Solares'),
('PNL-LONG450', 'Panel Longi Solar 450W Black Frame', 110.00, 'Paneles Solares'),
('INV-HUA-5K', 'Inversor Híbrido Huawei SUN2000-5KTL-L1', 850.00, 'Inversores'),
('INV-FRO-GEN24', 'Inversor Fronius Primo GEN24 6.0 Plus', 1250.00, 'Inversores'),
('INV-SMA-ST10', 'Inversor de Red SMA Sunny Tripower 10.0', 1890.00, 'Inversores'),
('BAT-LUNA-5', 'Módulo Batería Huawei LUNA2000 5kWh', 2100.00, 'Baterías y Almacenamiento'),
('BAT-BYD-HVS', 'Batería BYD Battery-Box Premium HVS 5.1', 2450.00, 'Baterías y Almacenamiento'),
('EST-ALU-01', 'Perfil Aluminio 40x40 (Barra 3m) para Coplanar', 25.50, 'Estructuras y Fijaciones'),
('EST-GRAPA-END', 'Grapa Final Ajustable 30-40mm Negro', 1.20, 'Estructuras y Fijaciones'),
('EST-GRAPA-MID', 'Grapa Intermedia 30-40mm Negro', 1.35, 'Estructuras y Fijaciones'),
('CAB-SOL-6MM', 'Cable Solar H1Z2Z2-K 6mm² Rojo (Rollo 100m)', 115.00, 'Material Eléctrico'),
('CAB-SOL-6MM-B', 'Cable Solar H1Z2Z2-K 6mm² Negro (Rollo 100m)', 115.00, 'Material Eléctrico'),
('CON-MC4', 'Pareja Conectores MC4 Stäubli Original', 2.50, 'Material Eléctrico'),
('PROT-DC-2', 'Cuadro Protección DC 2 Strings 1000V', 85.00, 'Material Eléctrico')
ON CONFLICT (cod_ref_producto) DO NOTHING;

-- 8.5 PROVEEDORES
INSERT INTO proveedores (nombre_comercial, razon_social, es_autonomo, cif, direccion_fiscal, creado_por)
SELECT * FROM (VALUES
    ('Electricidad García SL', 'Electricidad García Sociedad Limitada', FALSE, 'B12345678', 'Pol. Ind. Calonge, Calle A, 12, Sevilla', 'jefe_admin'),
    ('Carlos Fontanería', 'Carlos Pérez Gómez', TRUE, '12345678Z', 'Calle Betis 45, Sevilla', 'jefe_admin'),
    ('Construcciones Modesto', 'Modesto Construcciones SA', FALSE, 'A87654321', 'Avda. de la Paz 10, Alcalá de Guadaíra', 'jefe_admin'),
    ('Climatización Del Sur', 'ClimaSur Instalaciones SL', FALSE, 'B11223344', 'Calle Refrigeración 5, Dos Hermanas', 'jefe_admin'),
    ('Topografía y Medición', 'Ana Ruiz Topógrafa', TRUE, '23456789X', 'Plaza de Cuba 3, Sevilla', 'jefe_admin'),
    ('Carpintería Hnos. López', 'Carpintería López CB', FALSE, 'E55667788', 'Calle Madera 8, Utrera', 'jefe_admin'),
    ('Pinturas Lozano', 'Juan Lozano Pintor', TRUE, '34567890C', 'Calle Arco Iris 2, Mairena del Aljarafe', 'jefe_admin'),
    ('Silence Acústica', 'Ingeniería Silence SL', FALSE, 'B99887766', 'Parque Tecnológico Cartuja, Sevilla', 'jefe_admin'),
    ('Excavaciones Tierra', 'Excavaciones Tierra SL', FALSE, 'B44332211', 'Carretera Carmona Km 5', 'jefe_admin'),
    ('Seguridad 24h', 'Alarmas y Sistemas SL', FALSE, 'B66778899', 'Avda. República Argentina 20, Sevilla', 'jefe_admin')
) AS v(nombre, razon, autonomo, cif, direccion, creador)
WHERE NOT EXISTS (SELECT 1 FROM proveedores p WHERE p.cif = v.cif);

-- 8.6 TÉCNICOS INSTALADORES
INSERT INTO tecnicos_instaladores (nombre, telefono, activo) VALUES
('Juan Pérez', '600111222', TRUE),
('Andrés García', '600333444', TRUE),
('Luis Rodríguez', '600555666', FALSE)
ON CONFLICT (nombre) DO NOTHING;

-- 8.7 EMPLEADOS RRHH (Referencia)
INSERT INTO empleados (id, nombre_completo, dni_nie, fecha_alta, puesto, estado)
VALUES ('00000000-0000-0000-0000-000000000001', 'Administrador Jefe', '00000000T', CURRENT_DATE, 'Administrador', 'ACTIVO')
ON CONFLICT (dni_nie) DO NOTHING;

-- ---------------------------------------------------------
-- SECCIÓN 9: PARCHES DE SINCRONIZACIÓN (AUDITORÍA 2026-04-06)
-- ---------------------------------------------------------

-- 9.1 TABLA CITAS
CREATE TABLE IF NOT EXISTS citas (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    estado VARCHAR(255),
    enlace_remoto TEXT,
    notas TEXT,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    recordatorio_min INT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cita_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_cita_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario)
);

-- 9.2 TABLAS DE MANTENIMIENTO PREVENTIVO
CREATE TABLE IF NOT EXISTS presupuestos_preventivos (
    id_presupuesto_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    presupuesto_id BIGINT,
    fecha DATE NOT NULL,
    estado VARCHAR(255),
    notas TEXT,
    CONSTRAINT fk_prev_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_prev_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local),
    CONSTRAINT fk_prev_presupuesto FOREIGN KEY (presupuesto_id) REFERENCES presupuestos(id_presupuesto)
);

CREATE TABLE IF NOT EXISTS presupuestos_preventivos_tareas (
    id_tarea_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_tarea_prev_presup FOREIGN KEY (presupuesto_prev_id) REFERENCES presupuestos_preventivos(id_presupuesto_prev) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contratos_mantenimiento (
    id_contrato_mant BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    vivienda_id BIGINT NOT NULL,
    contrato_id BIGINT,
    fecha_inicio DATE NOT NULL,
    estado VARCHAR(255),
    creado_por VARCHAR(100),
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mant_prev FOREIGN KEY (presupuesto_prev_id) REFERENCES presupuestos_preventivos(id_presupuesto_prev),
    CONSTRAINT fk_mant_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_mant_vivienda FOREIGN KEY (vivienda_id) REFERENCES locales(id_local),
    CONSTRAINT fk_mant_contrato FOREIGN KEY (contrato_id) REFERENCES contratos(id_contrato)
);

CREATE TABLE IF NOT EXISTS contratos_mantenimiento_tareas (
    id_tarea_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_tarea_mant_contrato FOREIGN KEY (contrato_mant_id) REFERENCES contratos_mantenimiento(id_contrato_mant) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS avisos_mantenimiento (
    id_aviso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL,
    fecha_programada DATE NOT NULL,
    estado VARCHAR(255),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aviso_mant_contrato FOREIGN KEY (contrato_mant_id) REFERENCES contratos_mantenimiento(id_contrato_mant) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS avisos_mantenimiento_detalle (
    id_aviso_det BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aviso_id BIGINT NOT NULL,
    tarea_contrato_id BIGINT NOT NULL,
    estado VARCHAR(255),
    observaciones TEXT,
    CONSTRAINT fk_aviso_det_aviso FOREIGN KEY (aviso_id) REFERENCES avisos_mantenimiento(id_aviso) ON DELETE CASCADE,
    CONSTRAINT fk_aviso_det_tarea FOREIGN KEY (tarea_contrato_id) REFERENCES contratos_mantenimiento_tareas(id_tarea_contrato)
);

-- 9.3 CRM DOCUMENTS
CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    file_name_original VARCHAR(255) NOT NULL,
    file_name_system VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(50),
    size BIGINT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9.4 LÍNEAS DE ALBARANES Y FACTURAS (Faltantes)
CREATE TABLE IF NOT EXISTS albaranes_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albaran_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2),
    total_linea NUMERIC(12, 2),
    total_iva NUMERIC(12, 2),
    total_con_iva NUMERIC(12, 2),
    CONSTRAINT fk_alb_prov_linea FOREIGN KEY (albaran_id) REFERENCES albaranes_proveedor(id_albaran) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS albaranes_venta_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albaran_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2),
    total_linea NUMERIC(12, 2),
    total_iva NUMERIC(12, 2),
    total_con_iva NUMERIC(12, 2),
    CONSTRAINT fk_alb_venta_linea FOREIGN KEY (albaran_id) REFERENCES albaranes_venta(id_albaran) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS facturas_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id BIGINT NOT NULL,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2),
    total_linea NUMERIC(12, 2),
    total_iva NUMERIC(12, 2),
    total_con_iva NUMERIC(12, 2),
    CONSTRAINT fk_fact_prov_linea FOREIGN KEY (factura_id) REFERENCES facturas_proveedor(id_factura) ON DELETE CASCADE
);

-- Finalizar script
COMMIT;
