-- =========================================================
-- ESQUEMA DE BASE DE DATOS: GESTIÓN INGENIERÍA V2
-- AUDITORÍA Y RECONCILIACIÓN TOTAL: 2026-04-06
-- =========================================================

-- Configuración inicial
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ---------------------------------------------------------
-- NIVEL 1: TABLAS MAESTRAS (Sin dependencias externas)
-- ---------------------------------------------------------

-- 1.1 Usuarios del sistema
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(50), -- ADMIN, TÉCNICO, LECTURA
    email VARCHAR(100),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1.2 Clientes
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido1 VARCHAR(50) NOT NULL,
    apellido2 VARCHAR(50),
    dni VARCHAR(15) NOT NULL UNIQUE,
    direccion_fiscal_completa VARCHAR(255),
    codigo_postal VARCHAR(10),
    cuenta_bancaria VARCHAR(34),
    email VARCHAR(100),
    descripcion VARCHAR(255),
    creado_por VARCHAR(100),
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1.3 Proveedores
CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR(100) NOT NULL,
    razon_social VARCHAR(150),
    cif_nif VARCHAR(20) UNIQUE,
    email VARCHAR(100),
    telefono VARCHAR(20),
    direccion VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE
);

-- 1.4 Productos / Servicios
CREATE TABLE IF NOT EXISTS productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio_base NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21.00,
    activo BOOLEAN DEFAULT TRUE
);

-- 1.5 Técnicos Instaladores
CREATE TABLE IF NOT EXISTS tecnico_instalador (
    id_tecnico_instalador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dni VARCHAR(15) UNIQUE,
    especialidad VARCHAR(100),
    telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE
);

-- 1.6 Empleados (RRHH)
CREATE TABLE IF NOT EXISTS empleados (
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dni VARCHAR(15) UNIQUE NOT NULL,
    puesto VARCHAR(100),
    fecha_incorporacion DATE,
    estado_empleado VARCHAR(50) DEFAULT 'ACTIVO'
);

-- ---------------------------------------------------------
-- NIVEL 2: DEPENDENCIAS DE NIVEL 1
-- ---------------------------------------------------------

-- 2.1 Locales / Inmuebles
CREATE TABLE IF NOT EXISTS locales (
    id_local BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT REFERENCES clientes(id_cliente),
    nombre_titular VARCHAR(50) NOT NULL,
    apellido1_titular VARCHAR(50) NOT NULL,
    apellido2_titular VARCHAR(50),
    dni_titular VARCHAR(15),
    cups VARCHAR(22),
    referencia_catastral VARCHAR(20) NOT NULL UNIQUE,
    direccion_completa VARCHAR(255) NOT NULL,
    codigo_postal VARCHAR(10),
    localidad VARCHAR(100),
    provincia VARCHAR(100),
    latitud NUMERIC(10, 8),
    longitud NUMERIC(11, 8),
    creado_por VARCHAR(100),
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2.2 Teléfonos de Clientes
CREATE TABLE IF NOT EXISTS cliente_telefonos (
    id_telefono BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    numero VARCHAR(20) NOT NULL,
    tipo VARCHAR(50), -- Movil, Fijo, Trabajo
    es_principal BOOLEAN DEFAULT FALSE
);

-- 2.3 Ausencias, Fichajes (RRHH)
CREATE TABLE IF NOT EXISTS ausencias (
    id_ausencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL REFERENCES empleados(id_empleado),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    tipo_ausencia VARCHAR(50),
    estado_ausencia VARCHAR(50) DEFAULT 'PENDIENTE'
);

CREATE TABLE IF NOT EXISTS fichajes (
    id_fichaje BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL REFERENCES empleados(id_empleado),
    fecha_hora_entrada TIMESTAMP NOT NULL,
    fecha_hora_salida TIMESTAMP,
    latitud_entrada NUMERIC(10, 8),
    longitud_entrada NUMERIC(11, 8)
);

-- ---------------------------------------------------------
-- NIVEL 3: GESTIÓN COMERCIAL Y TÉCNICA
-- ---------------------------------------------------------

-- 3.1 Presupuestos
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id_cliente),
    vivienda_id BIGINT NOT NULL REFERENCES locales(id_local),
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2),
    total_sin_iva NUMERIC(12, 2),
    total_con_iva NUMERIC(12, 2),
    estado VARCHAR(255) DEFAULT 'Pendiente',
    tipo_presupuesto VARCHAR(255),
    descripcion TEXT,
    fecha_aceptacion TIMESTAMP,
    dias_validez INT DEFAULT 30
);

-- 3.2 Áreas de Locales
CREATE TABLE IF NOT EXISTS local_areas (
    id_local_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL REFERENCES locales(id_local) ON DELETE CASCADE,
    nombre_area VARCHAR(100) NOT NULL,
    metros_cuadrados NUMERIC(8, 2)
);

-- ---------------------------------------------------------
-- NIVEL 4: CONTRATOS Y DETALLES
-- ---------------------------------------------------------

-- 4.1 Contratos
CREATE TABLE IF NOT EXISTS contratos (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente),
    id_local BIGINT NOT NULL REFERENCES locales(id_local),
    id_presupuesto_origen BIGINT REFERENCES presupuestos(id_presupuesto),
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(255) NOT NULL,
    ce_previo VARCHAR(50),
    ce_post VARCHAR(50),
    enviado_cee_post BOOLEAN DEFAULT FALSE,
    forma_pago VARCHAR(255),
    nombre_financiera VARCHAR(255),
    fecha_inicio_financiacion DATE,
    importe_cuota NUMERIC(12, 2),
    importe_total_financiado NUMERIC(12, 2),
    porcentaje_contado NUMERIC(5, 2),
    licencia_obras VARCHAR(255),
    mtd BOOLEAN DEFAULT FALSE,
    planos BOOLEAN DEFAULT FALSE,
    subvencion_estado VARCHAR(255),
    libro_edif_incluido BOOLEAN DEFAULT FALSE,
    observaciones TEXT,
    estado VARCHAR(50) DEFAULT 'Activo',
    creado_por VARCHAR(100),
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4.2 Líneas de Presupuesto
CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    id_presupuesto_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_presupuesto BIGINT NOT NULL REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    id_producto BIGINT REFERENCES productos(id_producto),
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    descripcion TEXT,
    cantidad NUMERIC(12, 2) NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21.00,
    total_linea NUMERIC(12, 2)
);

-- ---------------------------------------------------------
-- NIVEL 5: INTERVENCIONES Y TRAMITACIÓN
-- ---------------------------------------------------------

-- 5.1 Trámites (Intervenciones)
CREATE TABLE IF NOT EXISTS tramites_contrato (
    id_tramite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato BIGINT NOT NULL REFERENCES contratos(id_contrato) ON DELETE CASCADE,
    tipo_tramite VARCHAR(255) NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    tecnico_asignado VARCHAR(255),
    fecha_seguimiento DATE,
    es_urgente BOOLEAN DEFAULT FALSE,
    facturado BOOLEAN DEFAULT FALSE,
    detalle_seguimiento TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion TIMESTAMP,
    id_tramite_bloqueante BIGINT REFERENCES tramites_contrato(id_tramite)
);

-- 5.2 Tabla puente para Técnicos en Trámites
CREATE TABLE IF NOT EXISTS tramite_instaladores (
    id_tramite BIGINT NOT NULL REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE,
    id_tecnico_instalador BIGINT NOT NULL REFERENCES tecnico_instalador(id_tecnico_instalador) ON DELETE CASCADE,
    PRIMARY KEY (id_tramite, id_tecnico_instalador)
);

-- 5.3 Citas
CREATE TABLE IF NOT EXISTS citas (
    id_cita BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id_usuario),
    titulo VARCHAR(150) NOT NULL,
    estado VARCHAR(255),
    enlace_remoto TEXT,
    notas TEXT,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    recordatorio_min INT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5.4 CRM Documents
CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    file_name_original VARCHAR(255) NOT NULL,
    file_name_system VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(50),
    size BIGINT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------
-- NIVEL 6: MANTENIMIENTO Y POST-VENTA
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS presupuestos_preventivos (
    id_presupuesto_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id_cliente),
    vivienda_id BIGINT NOT NULL REFERENCES locales(id_local),
    presupuesto_id BIGINT REFERENCES presupuestos(id_presupuesto),
    fecha DATE NOT NULL,
    estado VARCHAR(255),
    notas TEXT
);

CREATE TABLE IF NOT EXISTS presupuestos_preventivos_tareas (
    id_tarea_prev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL REFERENCES presupuestos_preventivos(id_presupuesto_prev) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS contratos_mantenimiento (
    id_contrato_mant BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_prev_id BIGINT NOT NULL REFERENCES presupuestos_preventivos(id_presupuesto_prev),
    cliente_id BIGINT NOT NULL REFERENCES clientes(id_cliente),
    vivienda_id BIGINT NOT NULL REFERENCES locales(id_local),
    contrato_id BIGINT REFERENCES contratos(id_contrato),
    fecha_inicio DATE NOT NULL,
    estado VARCHAR(255),
    creado_por VARCHAR(100),
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contratos_mantenimiento_tareas (
    id_tarea_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL REFERENCES contratos_mantenimiento(id_contrato_mant) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    frecuencia_meses INT NOT NULL,
    orden INT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS avisos_mantenimiento (
    id_aviso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contrato_mant_id BIGINT NOT NULL REFERENCES contratos_mantenimiento(id_contrato_mant) ON DELETE CASCADE,
    fecha_programada DATE NOT NULL,
    estado VARCHAR(255),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avisos_mantenimiento_detalle (
    id_aviso_det BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aviso_id BIGINT NOT NULL REFERENCES avisos_mantenimiento(id_aviso) ON DELETE CASCADE,
    tarea_contrato_id BIGINT NOT NULL REFERENCES contratos_mantenimiento_tareas(id_tarea_contrato),
    estado VARCHAR(255),
    observaciones TEXT
);

-- ---------------------------------------------------------
-- NIVEL 7: LOGÍSTICA Y LÍNEAS DE GASTO/VENTA
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS albaranes_proveedor (
    id_albaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL REFERENCES proveedores(id_proveedor),
    numero_albaran VARCHAR(50),
    fecha DATE,
    notas TEXT
);

CREATE TABLE IF NOT EXISTS albaranes_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    albaran_id BIGINT NOT NULL REFERENCES albaranes_proveedor(id_albaran) ON DELETE CASCADE,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2),
    total_linea NUMERIC(12, 2)
);

CREATE TABLE IF NOT EXISTS facturas_proveedor (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor BIGINT NOT NULL REFERENCES proveedores(id_proveedor),
    numero_factura VARCHAR(50),
    fecha DATE,
    total_importe NUMERIC(12, 2)
);

CREATE TABLE IF NOT EXISTS facturas_proveedor_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id BIGINT NOT NULL REFERENCES facturas_proveedor(id_factura) ON DELETE CASCADE,
    orden INT NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2),
    total_linea NUMERIC(12, 2)
);

-- Datos iniciales obligatorios
INSERT INTO usuarios (nombre_usuario, password_hash, rol) 
VALUES ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8q7Ou5f2L9.p69rYh3nZ.gG95b/f3M1g7S2', 'ADMIN')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- Finalizar script
COMMIT;

-- SECCIÓN 10: ALTER TABLES PARA PARCHES EXISTENTES
-- Ejecutar estas líneas si la base de datos ya existe y solo se desea añadir las nuevas columnas de dirección
-- ALTER TABLE locales ADD COLUMN IF NOT EXISTS codigo_postal VARCHAR(10);
-- ALTER TABLE locales ADD COLUMN IF NOT EXISTS localidad VARCHAR(100);
-- ALTER TABLE locales ADD COLUMN IF NOT EXISTS provincia VARCHAR(100);
