-- =========================================================
-- SCRIPT DE ESTRUCTURA TOTAL (SIN DATOS DE PRUEBA)
-- GESTIÓN INGENIERÍA V2 - CONSOLIDADO 2026-04-07
-- INCLUYE: Estructura Completa + Usuario jefe_admin y Manuel.
-- =========================================================

BEGIN;

-- ---------------------------------------------------------
-- 1. CONFIGURACIÓN Y EXTENSIONES
-- ---------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------
-- 2. TABLAS MAESTRAS
-- ---------------------------------------------------------

-- 2.1 Usuarios del sistema
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    dni VARCHAR(15) UNIQUE,
    rol VARCHAR(50) DEFAULT 'LECTURA',
    email VARCHAR(100),
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2.2 Clientes
CREATE TABLE IF NOT EXISTS clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido1 VARCHAR(50) NOT NULL,
    apellido2 VARCHAR(50),
    dni VARCHAR(15) NOT NULL UNIQUE,
    direccion_fiscal_completa VARCHAR(255),
    codigo_postal VARCHAR(10),
    cuenta_bancaria VARCHAR(34),
    email VARCHAR(100),
    descripcion VARCHAR(255),
    observaciones TEXT,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ
);

-- Refuerzo de esquema para entornos ya creados sin este campo
ALTER TABLE clientes
    ADD COLUMN IF NOT EXISTS observaciones TEXT;

-- 2.3 Proveedores
CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial VARCHAR(100) NOT NULL,
    razon_social VARCHAR(150),
    es_autonomo BOOLEAN DEFAULT FALSE,
    cif_nif VARCHAR(20) UNIQUE,
    email VARCHAR(100),
    telefono VARCHAR(20),
    direccion_fiscal VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2.4 Productos / Servicios
CREATE TABLE IF NOT EXISTS productos (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_ref_producto VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(150),
    descripcion VARCHAR(255) NOT NULL,
    coste NUMERIC(12, 2) NOT NULL,
    precio_base NUMERIC(12, 2),
    categoria VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE
);

-- 2.5 Técnicos Instaladores
CREATE TABLE IF NOT EXISTS tecnico_instalador (
    id_tecnico_instalador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dni VARCHAR(15) UNIQUE,
    especialidad VARCHAR(100),
    telefono VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE
);

-- 2.6 Empleados (RRHH)
CREATE TABLE IF NOT EXISTS empleados (
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    dni VARCHAR(15) UNIQUE NOT NULL,
    puesto VARCHAR(100),
    fecha_incorporacion DATE,
    estado_empleado VARCHAR(50) DEFAULT 'ACTIVO'
);

-- ---------------------------------------------------------
-- 3. TABLAS DE NIVEL 2 (DEPENDENCIAS)
-- ---------------------------------------------------------

-- 3.1 Locales / Inmuebles
CREATE TABLE IF NOT EXISTS locales (
    id_local BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    nombre_titular VARCHAR(50) NOT NULL,
    apellido1_titular VARCHAR(50) NOT NULL,
    apellido2_titular VARCHAR(50),
    dni_titular VARCHAR(15),
    cups VARCHAR(22),
    referencia_catastral VARCHAR(20),
    direccion_completa VARCHAR(255) NOT NULL,
    codigo_postal VARCHAR(10),
    localidad VARCHAR(100),
    provincia VARCHAR(100),
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ
);

-- 3.2 Teléfonos de Clientes
CREATE TABLE IF NOT EXISTS cliente_telefonos (
    id_telefono BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    numero VARCHAR(20) NOT NULL,
    tipo VARCHAR(50), 
    es_principal BOOLEAN DEFAULT FALSE
);

-- ---------------------------------------------------------
-- 4. GESTIÓN COMERCIAL Y COMUNICACIÓN
-- ---------------------------------------------------------

-- 4.1 Presupuestos
CREATE TABLE IF NOT EXISTS presupuestos (
    id_presupuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id_cliente),
    vivienda_id BIGINT NOT NULL REFERENCES locales(id_local),
    codigo_referencia VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    total NUMERIC(12, 2) DEFAULT 0,
    total_sin_iva NUMERIC(12, 2) DEFAULT 0,
    total_con_iva NUMERIC(12, 2) DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'Borrador',
    tipo_presupuesto VARCHAR(50) DEFAULT 'Obra',
    id_contrato BIGINT, -- Se añade FK después de crear contratos
    id_tramite BIGINT,
    fecha_aceptacion TIMESTAMPTZ,
    dias_validez INT DEFAULT 30
);

-- 4.2 Áreas Funcionales (Locales)
CREATE TABLE IF NOT EXISTS areas_funcionales (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local BIGINT NOT NULL REFERENCES locales(id_local) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    orden INTEGER
);

CREATE TABLE IF NOT EXISTS area_funcional_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area BIGINT NOT NULL REFERENCES areas_funcionales(id_area) ON DELETE CASCADE,
    producto_id BIGINT,
    producto_texto VARCHAR(255),
    concepto VARCHAR(255),
    cantidad NUMERIC(12, 2),
    accion_requerida VARCHAR(255),
    orden INTEGER
);

-- ---------------------------------------------------------
-- 5. CONTRATOS E INTERVENCIONES
-- ---------------------------------------------------------

-- 5.1 Contratos
CREATE TABLE IF NOT EXISTS contratos (
    id_contrato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    id_local BIGINT NOT NULL REFERENCES locales(id_local) ON DELETE CASCADE,
    id_presupuesto_origen BIGINT REFERENCES presupuestos(id_presupuesto) ON DELETE SET NULL,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(50) NOT NULL,
    ce_previo VARCHAR(50) DEFAULT 'Pendiente',
    ce_post VARCHAR(50) DEFAULT 'Pendiente',
    enviado_cee_post BOOLEAN DEFAULT FALSE,
    licencia_obras VARCHAR(255) DEFAULT 'No requerida',
    mtd BOOLEAN DEFAULT FALSE,
    planos BOOLEAN DEFAULT FALSE,
    subvencion_estado VARCHAR(255) DEFAULT 'No solicitada',
    libro_edif_incluido BOOLEAN DEFAULT FALSE,
    forma_pago VARCHAR(255) DEFAULT 'Al contado',
    nombre_financiera VARCHAR(255),
    fecha_inicio_financiacion DATE,
    importe_cuota NUMERIC(12, 2),
    importe_total_financiado NUMERIC(12, 2),
    porcentaje_contado NUMERIC(5, 2),
    observaciones TEXT,
    estado VARCHAR(50) DEFAULT 'Activo',
    creado_por VARCHAR(100) DEFAULT 'Sistema',
    modificado_por VARCHAR(100),
    fecha_alta TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ
);

-- FK Circular Presupuestos -> Contratos
ALTER TABLE presupuestos DROP CONSTRAINT IF EXISTS fk_presupuesto_contrato;
ALTER TABLE presupuestos ADD CONSTRAINT fk_presupuesto_contrato 
FOREIGN KEY (id_contrato) REFERENCES contratos(id_contrato) ON DELETE SET NULL;

-- 5.2 Trámites e Intervenciones
CREATE TABLE IF NOT EXISTS tramites_contrato (
    id_tramite BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato BIGINT NOT NULL REFERENCES contratos(id_contrato) ON DELETE CASCADE,
    tipo_tramite VARCHAR(255) NOT NULL,
    estado VARCHAR(255) DEFAULT 'Pendiente',
    tecnico_asignado VARCHAR(255),
    fecha_seguimiento DATE,
    es_urgente BOOLEAN DEFAULT FALSE,
    facturado BOOLEAN DEFAULT FALSE,
    detalle_seguimiento TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion TIMESTAMPTZ,
    id_tramite_bloqueante BIGINT REFERENCES tramites_contrato(id_tramite)
);

-- 5.3 Tabla Puente Instaladores
CREATE TABLE IF NOT EXISTS tramite_instaladores (
    id_tramite BIGINT NOT NULL REFERENCES tramites_contrato(id_tramite) ON DELETE CASCADE,
    id_tecnico_instalador BIGINT NOT NULL REFERENCES tecnico_instalador(id_tecnico_instalador) ON DELETE CASCADE,
    PRIMARY KEY (id_tramite, id_tecnico_instalador)
);

-- 5.4 Líneas de Presupuesto
CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    id_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT NOT NULL REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    orden INT NOT NULL,
    producto_id BIGINT REFERENCES productos(id_producto),
    producto_texto VARCHAR(255),
    concepto VARCHAR(255) NOT NULL,
    descripcion TEXT,
    cantidad NUMERIC(12, 2),
    precio_unitario NUMERIC(12, 2),
    coste_unitario NUMERIC(12, 2),
    factor_margen NUMERIC(6, 2) DEFAULT 1.00,
    total_coste NUMERIC(12, 2),
    pvp_unitario NUMERIC(12, 2),
    total_pvp NUMERIC(12, 2),
    importe_iva NUMERIC(12, 2),
    total_final NUMERIC(12, 2),
    iva_porcentaje NUMERIC(5, 2) DEFAULT 21.00,
    total_linea NUMERIC(12, 2),
    tipo_jerarquia VARCHAR(20) DEFAULT 'PARTIDA',
    codigo_visual VARCHAR(20),
    padre_id BIGINT REFERENCES presupuesto_lineas(id_linea) ON DELETE CASCADE,
    num_visitas INT DEFAULT 0
);

-- ---------------------------------------------------------
-- 6. AUDITORÍA, CHAT Y DOCUMENTOS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS auditoria_sistema (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(50),
    id_registro BIGINT,
    campo_modificado VARCHAR(50),
    valor_anterior TEXT,
    valor_nuevo TEXT,
    fecha_cambio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    usuario_bd VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS auditoria_sesiones (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    nombre_usuario VARCHAR(50) NOT NULL,
    fecha_inicio TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_fin TIMESTAMPTZ,
    fecha_ultima_actividad TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ip_acceso VARCHAR(45),
    estado VARCHAR(20) DEFAULT 'Conectado'
);

CREATE TABLE IF NOT EXISTS crm_documents (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    reference_id BIGINT NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    file_name_original VARCHAR(255) NOT NULL,
    file_name_system VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(50),
    size BIGINT,
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Chat Salas y Mensajes
CREATE TABLE IF NOT EXISTS chat_rooms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  is_group BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS chat_user_rooms (
  room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
  user_id UUID,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
  sender_id UUID,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------
-- 7. ÍNDICES DE RENDIMIENTO
-- ---------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_clientes_dni ON clientes(dni);
CREATE INDEX IF NOT EXISTS idx_locales_cliente ON locales(id_cliente);
CREATE INDEX IF NOT EXISTS idx_presupuestos_cliente ON presupuestos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_contratos_cliente ON contratos(id_cliente);
CREATE INDEX IF NOT EXISTS idx_crm_docs_ref ON crm_documents(entity_type, reference_id);

-- ---------------------------------------------------------
-- 8. DATOS INICIALES (SOLO USUARIOS REQUERIDOS)
-- ---------------------------------------------------------

-- Insertar jefe_admin si no existe
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) 
VALUES ('jefe_admin', '$2a$10$fx8sccd3svi33CcKUrH.BOfPEiC8Y.qWD1rYKkobZ2rporK45MmGi', 'ADMIN', 'jefeadmin@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

-- Insertar Manuel si no existe
INSERT INTO usuarios (nombre_usuario, password_hash, rol, email) 
VALUES ('Manuel', '$2a$10$ub6/aibpkSyqhORYDQceEehLI.pjBODVdPEkZED4bleFdMCujcK1a', 'ADMIN', 'manuel@insene.com')
ON CONFLICT (nombre_usuario) DO NOTHING;

COMMIT;
